// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: socketgtw.proto

package server

import (
	"context"

	"zero-service/socketapp/socketgtw/internal/logic"
	"zero-service/socketapp/socketgtw/internal/svc"
	"zero-service/socketapp/socketgtw/socketgtw"
)

type SocketGtwServer struct {
	svcCtx *svc.ServiceContext
	socketgtw.UnimplementedSocketGtwServer
}

func NewSocketGtwServer(svcCtx *svc.ServiceContext) *SocketGtwServer {
	return &SocketGtwServer{
		svcCtx: svcCtx,
	}
}

// 加入房间
func (s *SocketGtwServer) JoinRoom(ctx context.Context, in *socketgtw.JoinRoomReq) (*socketgtw.JoinRoomRes, error) {
	l := logic.NewJoinRoomLogic(ctx, s.svcCtx)
	return l.JoinRoom(in)
}

// 离开房间
func (s *SocketGtwServer) LeaveRoom(ctx context.Context, in *socketgtw.LeaveRoomReq) (*socketgtw.LeaveRoomRes, error) {
	l := logic.NewLeaveRoomLogic(ctx, s.svcCtx)
	return l.LeaveRoom(in)
}

// 向指定房间广播消息
func (s *SocketGtwServer) BroadcastRoom(ctx context.Context, in *socketgtw.BroadcastRoomReq) (*socketgtw.BroadcastRoomRes, error) {
	l := logic.NewBroadcastRoomLogic(ctx, s.svcCtx)
	return l.BroadcastRoom(in)
}

// 向所有在线前端广播消息
func (s *SocketGtwServer) BroadcastGlobal(ctx context.Context, in *socketgtw.BroadcastGlobalReq) (*socketgtw.BroadcastGlobalRes, error) {
	l := logic.NewBroadcastGlobalLogic(ctx, s.svcCtx)
	return l.BroadcastGlobal(in)
}

// 剔除 session
func (s *SocketGtwServer) KickSession(ctx context.Context, in *socketgtw.KickSessionReq) (*socketgtw.KickSessionRes, error) {
	l := logic.NewKickSessionLogic(ctx, s.svcCtx)
	return l.KickSession(in)
}
