// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ossFieldNames          = builder.RawFieldNames(&Oss{})
	ossRows                = strings.Join(ossFieldNames, ",")
	ossRowsExpectAutoSet   = strings.Join(stringx.Remove(ossFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ossRowsWithPlaceHolder = strings.Join(stringx.Remove(ossFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroOssIdPrefix              = "cache:zero:oss:id:"
	cacheZeroOssTenantIdOssCodePrefix = "cache:zero:oss:tenantId:ossCode:"
)

type (
	ossModel interface {
		Insert(ctx context.Context, data *Oss) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Oss, error)
		FindOneByTenantIdOssCode(ctx context.Context, tenantId string, ossCode string) (*Oss, error)
		Update(ctx context.Context, data *Oss) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOssModel struct {
		sqlc.CachedConn
		table string
	}

	Oss struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		Version    int64     `db:"version"`     // 版本号
		TenantId   string    `db:"tenant_id"`   // 租户ID
		Category   int64     `db:"category"`    // 分类 1-minio 2-qiniu 3-ali 4-tecent
		OssCode    string    `db:"oss_code"`    // 资源编号
		Endpoint   string    `db:"endpoint"`    // 资源地址
		AccessKey  string    `db:"access_key"`  // accessKey
		SecretKey  string    `db:"secret_key"`  // secretKey
		BucketName string    `db:"bucket_name"` // 空间名
		AppId      string    `db:"app_id"`      // 应用ID
		Region     string    `db:"region"`      // 地域简称
		Remark     string    `db:"remark"`      // 备注
		Status     int64     `db:"status"`      // 状态 1-开启 2-关闭
	}
)

func newOssModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOssModel {
	return &defaultOssModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`oss`",
	}
}

func (m *defaultOssModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	zeroOssIdKey := fmt.Sprintf("%s%v", cacheZeroOssIdPrefix, id)
	zeroOssTenantIdOssCodeKey := fmt.Sprintf("%s%v:%v", cacheZeroOssTenantIdOssCodePrefix, data.TenantId, data.OssCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroOssIdKey, zeroOssTenantIdOssCodeKey)
	return err
}

func (m *defaultOssModel) FindOne(ctx context.Context, id int64) (*Oss, error) {
	zeroOssIdKey := fmt.Sprintf("%s%v", cacheZeroOssIdPrefix, id)
	var resp Oss
	err := m.QueryRowCtx(ctx, &resp, zeroOssIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ossRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOssModel) FindOneByTenantIdOssCode(ctx context.Context, tenantId string, ossCode string) (*Oss, error) {
	zeroOssTenantIdOssCodeKey := fmt.Sprintf("%s%v:%v", cacheZeroOssTenantIdOssCodePrefix, tenantId, ossCode)
	var resp Oss
	err := m.QueryRowIndexCtx(ctx, &resp, zeroOssTenantIdOssCodeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `oss_code` = ? limit 1", ossRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, ossCode); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOssModel) Insert(ctx context.Context, data *Oss) (sql.Result, error) {
	zeroOssIdKey := fmt.Sprintf("%s%v", cacheZeroOssIdPrefix, data.Id)
	zeroOssTenantIdOssCodeKey := fmt.Sprintf("%s%v:%v", cacheZeroOssTenantIdOssCodePrefix, data.TenantId, data.OssCode)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, ossRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.TenantId, data.Category, data.OssCode, data.Endpoint, data.AccessKey, data.SecretKey, data.BucketName, data.AppId, data.Region, data.Remark, data.Status)
	}, zeroOssIdKey, zeroOssTenantIdOssCodeKey)
	return ret, err
}

func (m *defaultOssModel) Update(ctx context.Context, newData *Oss) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	zeroOssIdKey := fmt.Sprintf("%s%v", cacheZeroOssIdPrefix, data.Id)
	zeroOssTenantIdOssCodeKey := fmt.Sprintf("%s%v:%v", cacheZeroOssTenantIdOssCodePrefix, data.TenantId, data.OssCode)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ossRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.Version, newData.TenantId, newData.Category, newData.OssCode, newData.Endpoint, newData.AccessKey, newData.SecretKey, newData.BucketName, newData.AppId, newData.Region, newData.Remark, newData.Status, newData.Id)
	}, zeroOssIdKey, zeroOssTenantIdOssCodeKey)
	return err
}

func (m *defaultOssModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroOssIdPrefix, primary)
}

func (m *defaultOssModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ossRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOssModel) tableName() string {
	return m.table
}
