// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.1

package model

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

type (
	planExecItemModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *PlanExecItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PlanExecItem, error)
		FindOneByExecId(ctx context.Context, execId string) (*PlanExecItem, error)
		Update(ctx context.Context, session sqlx.Session, data *PlanExecItem) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *PlanExecItem) error
		Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ExecCtx(ctx context.Context, session sqlx.Session, query string, args ...any) (sql.Result, error)
		SelectWithBuilder(ctx context.Context, builder squirrel.SelectBuilder) ([]*PlanExecItem, error)
		SelectOneWithBuilder(ctx context.Context, builder squirrel.SelectBuilder) (*PlanExecItem, error)
		InsertWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.InsertBuilder) (sql.Result, error)
		UpdateWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.UpdateBuilder) (sql.Result, error)
		DeleteWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.DeleteBuilder) (sql.Result, error)
		SelectBuilder() squirrel.SelectBuilder
		InsertBuilder() squirrel.InsertBuilder
		UpdateBuilder() squirrel.UpdateBuilder
		DeleteBuilder() squirrel.DeleteBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, id int64) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy ...string) ([]*PlanExecItem, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy ...string) ([]*PlanExecItem, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy ...string) ([]*PlanExecItem, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*PlanExecItem, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*PlanExecItem, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultPlanExecItemModel struct {
		conn             sqlx.SqlConn
		table            string
		dbType           DatabaseType
		planExecItemRows string
	}

	PlanExecItem struct {
		Id               int64          `db:"id"`                // 自增主键ID
		CreateTime       time.Time      `db:"create_time"`       // 创建时间
		UpdateTime       time.Time      `db:"update_time"`       // 更新时间
		DeleteTime       sql.NullTime   `db:"delete_time"`       // 删除时间（软删除标记）
		DelState         int64          `db:"del_state"`         // 删除状态：0-未删除，1-已删除
		Version          int64          `db:"version"`           // 版本号（乐观锁）
		CreateUser       sql.NullString `db:"create_user"`       // 创建人
		UpdateUser       sql.NullString `db:"update_user"`       // 更新人
		DeptCode         sql.NullString `db:"dept_code"`         // 机构code
		PlanPk           int64          `db:"plan_pk"`           // 关联的计划主键ID
		PlanId           string         `db:"plan_id"`           // 关联的计划ID
		BatchPk          int64          `db:"batch_pk"`          // 批主键ID
		BatchId          string         `db:"batch_id"`          // 批ID
		ExecId           string         `db:"exec_id"`           // 执行ID
		ItemId           string         `db:"item_id"`           // 执行项ID
		ItemType         sql.NullString `db:"item_type"`         // 执行项类型
		ItemName         sql.NullString `db:"item_name"`         // 执行项名称
		PointId          sql.NullString `db:"point_id"`          // 点位id
		ServiceAddr      string         `db:"service_addr"`      // 业务服务地址
		Payload          string         `db:"payload"`           // 业务负载
		RequestTimeout   int64          `db:"request_timeout"`   // 请求超时时间（毫秒）
		PlanTriggerTime  time.Time      `db:"plan_trigger_time"` // 计划触发时间
		NextTriggerTime  time.Time      `db:"next_trigger_time"` // 下次触发时间（扫表核心字段）
		LastTriggerTime  sql.NullTime   `db:"last_trigger_time"` // 上次触发时间
		TriggerCount     int64          `db:"trigger_count"`     // 触发次数
		Status           int64          `db:"status"`            // 状态：0-等待调度，10-延期等待，100-执行中，150-暂停，200-完成，300-终止
		LastResult       sql.NullString `db:"last_result"`       // 上次执行结果
		LastMessage      sql.NullString `db:"last_message"`      // 上次结果描述
		LastReason       sql.NullString `db:"last_reason"`       // 上次结果原因
		TerminatedTime   sql.NullTime   `db:"terminated_time"`   // 终止时间
		TerminatedReason sql.NullString `db:"terminated_reason"` // 终止原因
		PausedTime       sql.NullTime   `db:"paused_time"`       // 暂停时间
		PausedReason     sql.NullString `db:"paused_reason"`     // 暂停原因
		CompletedTime    sql.NullTime   `db:"completed_time"`    // 完成时间
		Ext1             sql.NullString `db:"ext_1"`             // 扩展字段1
		Ext2             sql.NullString `db:"ext_2"`             // 扩展字段2
		Ext3             sql.NullString `db:"ext_3"`             // 扩展字段3
		Ext4             sql.NullString `db:"ext_4"`             // 扩展字段4
		Ext5             sql.NullString `db:"ext_5"`             // 扩展字段5
	}
)

func newPlanExecItemModel(conn sqlx.SqlConn, dbType DatabaseType) *defaultPlanExecItemModel {
	tableName := "plan_exec_item"
	fieldNames := builder.RawFieldNames(&PlanExecItem{}, true)
	rows := strings.Join(fieldNames, ",")
	return &defaultPlanExecItemModel{
		conn:             conn,
		table:            tableName,
		dbType:           dbType,
		planExecItemRows: rows,
	}
}

func (m *defaultPlanExecItemModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	deleteBuilder := m.DeleteBuilder().Where("id = ?", id)
	query, args, err := deleteBuilder.ToSql()
	if err != nil {
		return err
	}
	var execErr error
	if session != nil {
		_, execErr = session.ExecCtx(ctx, query, args...)
	} else {
		_, execErr = m.conn.ExecCtx(ctx, query, args...)
	}
	return execErr
}

func (m *defaultPlanExecItemModel) FindOne(ctx context.Context, id int64) (*PlanExecItem, error) {
	selectBuilder := m.SelectBuilder().Columns(m.planExecItemRows).
		Where("id = ?", id).
		Where("del_state = ?", 0).
		Limit(1)
	query, args, err := selectBuilder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp PlanExecItem
	err = m.conn.QueryRowCtx(ctx, &resp, query, args...)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlanExecItemModel) FindOneByExecId(ctx context.Context, execId string) (*PlanExecItem, error) {
	selectBuilder := m.SelectBuilder().Columns(m.planExecItemRows).
		Where("exec_id = ?", execId).
		Where("del_state = ?", 0).
		Limit(1)
	query, args, err := selectBuilder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp PlanExecItem
	err = m.conn.QueryRowCtx(ctx, &resp, query, args...)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlanExecItemModel) Insert(ctx context.Context, session sqlx.Session, data *PlanExecItem) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{
		Valid: false,
	}
	data.DelState = 0
	columns, values := generateColumnsAndValues(data, []string{})
	insertBuilder := m.InsertBuilder().Columns(columns...).Values(values...)
	query, args, err := insertBuilder.ToSql()
	if err != nil {
		return nil, err
	}
	var result sql.Result
	var execErr error
	if session != nil {
		result, execErr = session.ExecCtx(ctx, query, args...)
	} else {
		result, execErr = m.conn.ExecCtx(ctx, query, args...)
	}
	return result, execErr
}

func (m *defaultPlanExecItemModel) Update(ctx context.Context, session sqlx.Session, data *PlanExecItem) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{
		Valid: false,
	}
	data.DelState = 0
	columns, values := generateColumnsAndValues(data, []string{})
	updateBuilder := m.UpdateBuilder()
	for i, column := range columns {
		updateBuilder = updateBuilder.Set(column, values[i])
	}
	updateBuilder = updateBuilder.Where("id = ?", data.Id)
	query, args, err := updateBuilder.ToSql()
	if err != nil {
		return nil, err
	}
	var result sql.Result
	var execErr error
	if session != nil {
		result, execErr = session.ExecCtx(ctx, query, args...)
	} else {
		result, execErr = m.conn.ExecCtx(ctx, query, args...)
	}
	return result, execErr
}

func (m *defaultPlanExecItemModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *PlanExecItem) error {
	oldVersion := data.Version
	data.Version += 1
	columns, values := generateColumnsAndValues(data, []string{})
	updateBuilder := m.UpdateBuilder()
	for i, column := range columns {
		updateBuilder = updateBuilder.Set(column, values[i])
	}
	updateBuilder = updateBuilder.Where("id = ?", data.Id).Where("version = ?", oldVersion)
	query, args, err := updateBuilder.ToSql()
	if err != nil {
		return err
	}
	var sqlResult sql.Result
	var execErr error
	if session != nil {
		sqlResult, execErr = session.ExecCtx(ctx, query, args...)
	} else {
		sqlResult, execErr = m.conn.ExecCtx(ctx, query, args...)
	}
	if execErr != nil {
		return execErr
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}
	return nil
}

func (m *defaultPlanExecItemModel) DeleteSoft(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	data.DelState = 1
	data.DeleteTime = sql.NullTime{
		Time:  time.Now(),
		Valid: true,
	}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "PlanExecItemModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultPlanExecItemModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {
	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}
	builder = builder.Columns("COALESCE(SUM(" + field + "),0)")
	query, values, err := builder.Where("del_state = ?", 0).ToSql()
	if err != nil {
		return 0, err
	}
	var resp float64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultPlanExecItemModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {
	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}
	builder = builder.Columns("COUNT(" + field + ")")
	query, values, err := builder.Where("del_state = ?", 0).ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultPlanExecItemModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy ...string) ([]*PlanExecItem, error) {
	builder = builder.Columns(m.planExecItemRows)
	if len(orderBy) == 0 {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy...)
	}
	query, values, err := builder.Where("del_state = ?", 0).ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecItem
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecItemModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy ...string) ([]*PlanExecItem, error) {
	builder = builder.Columns(m.planExecItemRows)
	if len(orderBy) == 0 {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy...)
	}
	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize
	query, values, err := builder.Where("del_state = ?", 0).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecItem
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecItemModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy ...string) ([]*PlanExecItem, int64, error) {
	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}
	builder = builder.Columns(m.planExecItemRows)
	if len(orderBy) == 0 {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy...)
	}
	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize
	query, values, err := builder.Where("del_state = ?", 0).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}
	var resp []*PlanExecItem
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultPlanExecItemModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*PlanExecItem, error) {
	builder = builder.Columns(m.planExecItemRows)
	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}
	query, values, err := builder.Where("del_state = ?", 0).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecItem
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecItemModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*PlanExecItem, error) {
	builder = builder.Columns(m.planExecItemRows)
	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}
	query, values, err := builder.Where("del_state = ?", 0).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecItem
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecItemModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {
	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultPlanExecItemModel) ExecCtx(ctx context.Context, session sqlx.Session, query string, args ...any) (sql.Result, error) {
	if session != nil {
		return session.ExecCtx(ctx, query, args...)
	}
	return m.conn.ExecCtx(ctx, query, args...)
}

func (m *defaultPlanExecItemModel) SelectWithBuilder(ctx context.Context, builder squirrel.SelectBuilder) ([]*PlanExecItem, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecItem
	err = m.conn.QueryRowsPartialCtx(ctx, &resp, query, args...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecItemModel) SelectOneWithBuilder(ctx context.Context, builder squirrel.SelectBuilder) (*PlanExecItem, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp PlanExecItem
	err = m.conn.QueryRowPartialCtx(ctx, &resp, query, args...)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlanExecItemModel) InsertWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.InsertBuilder) (sql.Result, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.ExecCtx(ctx, session, query, args...)
}

func (m *defaultPlanExecItemModel) UpdateWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.UpdateBuilder) (sql.Result, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.ExecCtx(ctx, session, query, args...)
}

func (m *defaultPlanExecItemModel) DeleteWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.DeleteBuilder) (sql.Result, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.ExecCtx(ctx, session, query, args...)
}

func (m *defaultPlanExecItemModel) SelectBuilder() squirrel.SelectBuilder {
	if m.dbType == DatabaseTypePostgres {
		return squirrel.Select().From(m.table).PlaceholderFormat(squirrel.Dollar)
	}
	return squirrel.Select().From(m.table)
}

func (m *defaultPlanExecItemModel) UpdateBuilder() squirrel.UpdateBuilder {
	if m.dbType == DatabaseTypePostgres {
		return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
	}
	return squirrel.Update(m.table)
}

func (m *defaultPlanExecItemModel) DeleteBuilder() squirrel.DeleteBuilder {
	if m.dbType == DatabaseTypePostgres {
		return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
	}
	return squirrel.Delete(m.table)
}

func (m *defaultPlanExecItemModel) InsertBuilder() squirrel.InsertBuilder {
	if m.dbType == DatabaseTypePostgres {
		return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
	}
	return squirrel.Insert(m.table)
}

func (m *defaultPlanExecItemModel) tableName() string {
	return m.table
}
