// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.1

package model

import (
	"context"
	"database/sql"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

type (
	planExecLogModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *PlanExecLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PlanExecLog, error)
		Update(ctx context.Context, session sqlx.Session, data *PlanExecLog) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *PlanExecLog) error
		Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error
		ExecCtx(ctx context.Context, session sqlx.Session, query string, args ...any) (sql.Result, error)
		SelectWithBuilder(ctx context.Context, builder squirrel.SelectBuilder) ([]*PlanExecLog, error)
		SelectOneWithBuilder(ctx context.Context, builder squirrel.SelectBuilder) (*PlanExecLog, error)
		InsertWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.InsertBuilder) (sql.Result, error)
		UpdateWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.UpdateBuilder) (sql.Result, error)
		DeleteWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.DeleteBuilder) (sql.Result, error)
		SelectBuilder() squirrel.SelectBuilder
		InsertBuilder() squirrel.InsertBuilder
		UpdateBuilder() squirrel.UpdateBuilder
		DeleteBuilder() squirrel.DeleteBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, id int64) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy ...string) ([]*PlanExecLog, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy ...string) ([]*PlanExecLog, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy ...string) ([]*PlanExecLog, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*PlanExecLog, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*PlanExecLog, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultPlanExecLogModel struct {
		conn            sqlx.SqlConn
		table           string
		dbType          DatabaseType
		planExecLogRows string
	}

	PlanExecLog struct {
		Id          int64          `db:"id"`           // 自增主键ID
		CreateTime  time.Time      `db:"create_time"`  // 创建时间
		UpdateTime  time.Time      `db:"update_time"`  // 更新时间
		DeleteTime  sql.NullTime   `db:"delete_time"`  // 删除时间（软删除标记）
		DelState    int64          `db:"del_state"`    // 删除状态：0-未删除，1-已删除
		Version     int64          `db:"version"`      // 版本号（乐观锁）
		CreateUser  sql.NullString `db:"create_user"`  // 创建人
		UpdateUser  sql.NullString `db:"update_user"`  // 更新人
		PlanPk      int64          `db:"plan_pk"`      // 关联的计划主键ID
		PlanId      string         `db:"plan_id"`      // 计划任务ID
		PlanName    sql.NullString `db:"plan_name"`    // 计划任务名称
		BatchPk     int64          `db:"batch_pk"`     // 批主键ID
		BatchId     string         `db:"batch_id"`     // 批ID
		ItemPk      int64          `db:"item_pk"`      // 关联的执行项主键ID
		ItemId      string         `db:"item_id"`      // 执行项ID
		ItemName    sql.NullString `db:"item_name"`    // 执行项名称
		PointId     sql.NullString `db:"point_id"`     // 点位id
		TriggerTime time.Time      `db:"trigger_time"` // 触发时间
		TraceId     sql.NullString `db:"trace_id"`     // 唯一追踪ID
		ExecResult  sql.NullString `db:"exec_result"`  // 执行结果：1-成功，2-失败，3-延期
		Message     sql.NullString `db:"message"`      // 结果描述
	}
)

func newPlanExecLogModel(conn sqlx.SqlConn) *defaultPlanExecLogModel {
	return newPlanExecLogModelWithDBType(conn, DatabaseTypeMySQL)
}

func newPlanExecLogModelWithDBType(conn sqlx.SqlConn, dbType DatabaseType) *defaultPlanExecLogModel {
	isPostgreSQL := dbType == DatabaseTypePostgreSQL
	tableName := "plan_exec_log"
	fieldNames := builder.RawFieldNames(&PlanExecLog{}, isPostgreSQL)
	rows := strings.Join(fieldNames, ",")
	return &defaultPlanExecLogModel{
		conn:            conn,
		table:           tableName,
		dbType:          dbType,
		planExecLogRows: rows,
	}
}

func (m *defaultPlanExecLogModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	deleteBuilder := m.DeleteBuilder().Where("id = ?", id)
	query, args, err := deleteBuilder.ToSql()
	if err != nil {
		return err
	}
	var execErr error
	if session != nil {
		_, execErr = session.ExecCtx(ctx, query, args...)
	} else {
		_, execErr = m.conn.ExecCtx(ctx, query, args...)
	}
	return execErr
}
func (m *defaultPlanExecLogModel) FindOne(ctx context.Context, id int64) (*PlanExecLog, error) {
	selectBuilder := m.SelectBuilder().Columns(m.planExecLogRows).
		Where("id = ?", id).
		Where("del_state = ?", 0).
		Limit(1)
	query, args, err := selectBuilder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp PlanExecLog
	err = m.conn.QueryRowCtx(ctx, &resp, query, args...)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlanExecLogModel) Insert(ctx context.Context, session sqlx.Session, data *PlanExecLog) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{
		Valid: false,
	}
	data.DelState = 0
	columns, values := generateColumnsAndValues(data, []string{})
	insertBuilder := m.InsertBuilder().Columns(columns...).Values(values...)
	query, args, err := insertBuilder.ToSql()
	if err != nil {
		return nil, err
	}
	var result sql.Result
	var execErr error
	if session != nil {
		result, execErr = session.ExecCtx(ctx, query, args...)
	} else {
		result, execErr = m.conn.ExecCtx(ctx, query, args...)
	}
	return result, execErr
}

func (m *defaultPlanExecLogModel) Update(ctx context.Context, session sqlx.Session, data *PlanExecLog) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{
		Valid: false,
	}
	data.DelState = 0
	columns, values := generateColumnsAndValues(data, []string{})
	updateBuilder := m.UpdateBuilder()
	for i, column := range columns {
		updateBuilder = updateBuilder.Set(column, values[i])
	}
	updateBuilder = updateBuilder.Where("id = ?", data.Id)
	query, args, err := updateBuilder.ToSql()
	if err != nil {
		return nil, err
	}
	var result sql.Result
	var execErr error
	if session != nil {
		result, execErr = session.ExecCtx(ctx, query, args...)
	} else {
		result, execErr = m.conn.ExecCtx(ctx, query, args...)
	}
	return result, execErr
}

func (m *defaultPlanExecLogModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *PlanExecLog) error {
	oldVersion := data.Version
	data.Version += 1
	data.DeleteTime = sql.NullTime{
		Valid: false,
	}
	data.DelState = 0
	columns, values := generateColumnsAndValues(data, []string{})
	updateBuilder := m.UpdateBuilder()
	for i, column := range columns {
		updateBuilder = updateBuilder.Set(column, values[i])
	}
	updateBuilder = updateBuilder.Where("id = ?", data.Id).Where("version = ?", oldVersion)
	query, args, err := updateBuilder.ToSql()
	if err != nil {
		return err
	}
	var sqlResult sql.Result
	var execErr error
	if session != nil {
		sqlResult, execErr = session.ExecCtx(ctx, query, args...)
	} else {
		sqlResult, execErr = m.conn.ExecCtx(ctx, query, args...)
	}
	if execErr != nil {
		return execErr
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}
	return nil
}

func (m *defaultPlanExecLogModel) DeleteSoft(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	data.DelState = 1
	data.DeleteTime = sql.NullTime{
		Time:  time.Now(),
		Valid: true,
	}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "PlanExecLogModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultPlanExecLogModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {
	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}
	sumFunction := "COALESCE(SUM(" + field + "),0)"
	builder = builder.Columns(sumFunction)
	query, values, err := builder.Where("del_state = ?", 0).ToSql()
	if err != nil {
		return 0, err
	}
	var resp float64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultPlanExecLogModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {
	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}
	builder = builder.Columns("COUNT(" + field + ")")
	query, values, err := builder.Where("del_state = ?", 0).ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultPlanExecLogModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy ...string) ([]*PlanExecLog, error) {
	builder = builder.Columns(m.planExecLogRows)
	if len(orderBy) == 0 {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy...)
	}
	query, values, err := builder.Where("del_state = ?", 0).ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecLog
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecLogModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy ...string) ([]*PlanExecLog, error) {
	builder = builder.Columns(m.planExecLogRows)
	if len(orderBy) == 0 {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy...)
	}
	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize
	query, values, err := builder.Where("del_state = ?", 0).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecLog
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecLogModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy ...string) ([]*PlanExecLog, int64, error) {
	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}
	builder = builder.Columns(m.planExecLogRows)
	if len(orderBy) == 0 {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy...)
	}
	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize
	query, values, err := builder.Where("del_state = ?", 0).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}
	var resp []*PlanExecLog
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultPlanExecLogModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*PlanExecLog, error) {
	builder = builder.Columns(m.planExecLogRows)
	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}
	query, values, err := builder.Where("del_state = ?", 0).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecLog
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecLogModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*PlanExecLog, error) {
	builder = builder.Columns(m.planExecLogRows)
	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}
	query, values, err := builder.Where("del_state = ?", 0).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecLog
	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecLogModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {
	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultPlanExecLogModel) ExecCtx(ctx context.Context, session sqlx.Session, query string, args ...any) (sql.Result, error) {
	if session != nil {
		return session.ExecCtx(ctx, query, args...)
	}
	return m.conn.ExecCtx(ctx, query, args...)
}

func (m *defaultPlanExecLogModel) SelectWithBuilder(ctx context.Context, builder squirrel.SelectBuilder) ([]*PlanExecLog, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*PlanExecLog
	err = m.conn.QueryRowsPartialCtx(ctx, &resp, query, args...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultPlanExecLogModel) SelectOneWithBuilder(ctx context.Context, builder squirrel.SelectBuilder) (*PlanExecLog, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp PlanExecLog
	err = m.conn.QueryRowPartialCtx(ctx, &resp, query, args...)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlanExecLogModel) InsertWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.InsertBuilder) (sql.Result, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.ExecCtx(ctx, session, query, args...)
}

func (m *defaultPlanExecLogModel) UpdateWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.UpdateBuilder) (sql.Result, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.ExecCtx(ctx, session, query, args...)
}

func (m *defaultPlanExecLogModel) DeleteWithBuilder(ctx context.Context, session sqlx.Session, builder squirrel.DeleteBuilder) (sql.Result, error) {
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.ExecCtx(ctx, session, query, args...)
}

func (m *defaultPlanExecLogModel) SelectBuilder() squirrel.SelectBuilder {
	builder := squirrel.Select().From(m.table)
	if m.dbType == DatabaseTypePostgreSQL {
		builder = builder.PlaceholderFormat(squirrel.Dollar)
	}
	return builder
}

func (m *defaultPlanExecLogModel) UpdateBuilder() squirrel.UpdateBuilder {
	builder := squirrel.Update(m.table)
	if m.dbType == DatabaseTypePostgreSQL {
		builder = builder.PlaceholderFormat(squirrel.Dollar)
	}
	return builder
}

func (m *defaultPlanExecLogModel) DeleteBuilder() squirrel.DeleteBuilder {
	builder := squirrel.Delete(m.table)
	if m.dbType == DatabaseTypePostgreSQL {
		builder = builder.PlaceholderFormat(squirrel.Dollar)
	}
	return builder
}

func (m *defaultPlanExecLogModel) InsertBuilder() squirrel.InsertBuilder {
	builder := squirrel.Insert(m.table)
	if m.dbType == DatabaseTypePostgreSQL {
		builder = builder.PlaceholderFormat(squirrel.Dollar)
	}
	return builder
}

func (m *defaultPlanExecLogModel) tableName() string {
	return m.table
}
