// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type BaseRequest struct {
	Id int64 `json:"id"` // 主键ID
}

type DownloadFileRequest struct {
	Path string `form:"path"` // 文件路径
}

type EditCurrentUserReply struct {
}

type EditCurrentUserRequest struct {
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
}

type EmptyReply struct {
}

type File struct {
	Link         string `json:"link"`               // 文件地址
	Domain       string `json:"domain"`             // 域名地址
	Name         string `json:"name"`               // 文件名
	Size         int64  `json:"size"`               // 文件大小
	FormatSize   string `json:"formatSize"`         // 格式化文件大小
	OriginalName string `json:"originalName"`       // 初始文件名
	AttachId     string `json:"attachId,omitempty"` // 附件表ID
}

type ForwardReply struct {
}

type ForwardRequest struct {
	MsgId string `json:"msgId"`
	Body  string `json:"body"`
}

type GetCurrentUserReply struct {
	User User `json:"user"`
}

type GetCurrentUserRequest struct {
}

type GetFileReply struct {
	File File `json:"file"`
}

type GetRegionListReply struct {
	Region []Region `json:"region"`
}

type GetRegionListRequest struct {
	ParentCode string `json:"parentCode"` // 父区划编号
}

type ImageMeta struct {
	Longitude   float64 `json:"longitude"`   // 经度
	Latitude    float64 `json:"latitude"`    // 纬度
	Time        string  `json:"time"`        // 拍摄时间
	ImgHeight   int     `json:"imgHeight"`   // 高
	ImgWidth    int     `json:"imgWidth"`    // 宽
	Altitude    float64 `json:"altitude"`    // 高度
	CameraModel string  `json:"cameraModel"` // 相机型号
}

type LoginReply struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginRequest struct {
	AuthType string `json:"authType"` // miniProgram-小程序一键登录,mobile-手机号
	AuthKey  string `json:"authKey"`  // miniProgram-Code,mobile-验证码
	Password string `json:"password,optional"`
}

type MiniProgramLoginReply struct {
	OpenId     string `json:"openId"`
	UnionId    string `json:"unionId"`
	SessionKey string `json:"sessionKey"`
}

type MiniProgramLoginRequest struct {
	Code string `json:"code"`
}

type OssFile struct {
	Link        string `json:"link"`        // 文件地址
	Name        string `json:"name"`        // 文件名
	Size        int64  `json:"size"`        // 文件大小
	FormatSize  string `json:"formatSize"`  // 格式化文件大小
	PutTime     string `json:"putTime"`     // 文件上传时间
	ContentType string `json:"contentType"` // 文件contentType
	SignUrl     string `json:"signUrl"`     // 签名URL
}

type PingReply struct {
	Msg string `json:"msg"`
}

type PutFileRequest struct {
	TenantId   string `form:"tenantId"`   // 租户ID
	Code       string `form:"code"`       // 资源编号
	BucketName string `form:"bucketName"` // 存储桶名称
}

type Region struct {
	Code         string `json:"code"`         // 区划编号
	ParentCode   string `json:"parentCode"`   // 父区划编号
	Name         string `json:"name"`         // 区划名称
	ProvinceCode string `json:"provinceCode"` // 省级区划编号
	ProvinceName string `json:"provinceName"` // 省级名称
	CityCode     string `json:"cityCode"`     // 市级区划编号
	CityName     string `json:"cityName"`     // 市级名称
	DistrictCode string `json:"districtCode"` // 区级区划编号
	DistrictName string `json:"districtName"` // 区级名称
	RegionLevel  int64  `json:"regionLevel"`  // 层级
}

type SendSMSVerifyCodeReply struct {
	Code string `json:"code"`
}

type SendSMSVerifyCodeRequest struct {
	Mobile string `json:"mobile"`
}

type SignUrlReqly struct {
	Url string `json:"url"` // 文件url
}

type SignUrlRequest struct {
	TenantId   string `json:"tenantId"`   // 租户ID
	Code       string `json:"code"`       // 资源编号
	BucketName string `json:"bucketName"` // 存储桶名称
	Filename   string `json:"filename"`   // 文件名
	Expires    int32  `json:"expires"`    // 过期时间 默认一小时 单位分钟
}

type StatFileReply struct {
	OssFile OssFile `json:"ossFile"`
}

type StatFileRequest struct {
	TenantId   string `json:"tenantId"`   // 租户ID
	Code       string `json:"code"`       // 资源编号
	BucketName string `json:"bucketName"` // 存储桶名称
	Filename   string `json:"filename"`   // 文件名
	IsSign     bool   `json:"isSign"`     // 是否生成签名
	Expires    int32  `json:"expires"`    // 过期时间 默认一小时 单位分钟
}

type TenantRequest struct {
	Id       int64  `json:"id"`       // 主键ID
	TenantId string `json:"tenantId"` // 租户ID
}

type UploadFileReply struct {
	Name        string    `json:"name"`           // 文件名
	Path        string    `json:"path"`           // 文件路径
	Size        int64     `json:"size"`           // 文件大小
	ContextType string    `json:"contextType"`    // 文件类型
	Url         string    `json:"url"`            // 文件下载
	Meta        ImageMeta `json:"meta,omitempty"` // 图片 EXIF 信息
}

type UploadFileRequest struct {
	MfsType int64 `json:"status,options=1|2,optional"` // 文件类型 1-临时文件 2-业务文件
}

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
}
