// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: streamevent.proto

package streamevent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamEvent_ReceiveMQTTMessage_FullMethodName   = "/streamevent.StreamEvent/ReceiveMQTTMessage"
	StreamEvent_ReceiveWSMessage_FullMethodName     = "/streamevent.StreamEvent/ReceiveWSMessage"
	StreamEvent_ReceiveKafkaMessage_FullMethodName  = "/streamevent.StreamEvent/ReceiveKafkaMessage"
	StreamEvent_PushChunkAsdu_FullMethodName        = "/streamevent.StreamEvent/PushChunkAsdu"
	StreamEvent_UpSocketMessage_FullMethodName      = "/streamevent.StreamEvent/UpSocketMessage"
	StreamEvent_HandlerPlanTaskEvent_FullMethodName = "/streamevent.StreamEvent/HandlerPlanTaskEvent"
	StreamEvent_NotifyPlanEvent_FullMethodName      = "/streamevent.StreamEvent/NotifyPlanEvent"
)

// StreamEventClient is the client API for StreamEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamEventClient interface {
	// 接收MQTT消息
	ReceiveMQTTMessage(ctx context.Context, in *ReceiveMQTTMessageReq, opts ...grpc.CallOption) (*ReceiveMQTTMessageRes, error)
	// 接收WS消息
	ReceiveWSMessage(ctx context.Context, in *ReceiveWSMessageReq, opts ...grpc.CallOption) (*ReceiveWSMessageRes, error)
	// 接收kafka消息
	ReceiveKafkaMessage(ctx context.Context, in *ReceiveKafkaMessageReq, opts ...grpc.CallOption) (*ReceiveKafkaMessageRes, error)
	// 推送 chunk asdu 104协议消息
	PushChunkAsdu(ctx context.Context, in *PushChunkAsduReq, opts ...grpc.CallOption) (*PushChunkAsduRes, error)
	// 上行socket标准消息, 可以用于__up__和自定义up事件
	UpSocketMessage(ctx context.Context, in *UpSocketMessageReq, opts ...grpc.CallOption) (*UpSocketMessageReq, error)
	// 计划任务事件处理
	HandlerPlanTaskEvent(ctx context.Context, in *HandlerPlanTaskEventReq, opts ...grpc.CallOption) (*HandlerPlanTaskEventRes, error)
	// 通知计划任务事件
	NotifyPlanEvent(ctx context.Context, in *NotifyPlanEventReq, opts ...grpc.CallOption) (*NotifyPlanEventRes, error)
}

type streamEventClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamEventClient(cc grpc.ClientConnInterface) StreamEventClient {
	return &streamEventClient{cc}
}

func (c *streamEventClient) ReceiveMQTTMessage(ctx context.Context, in *ReceiveMQTTMessageReq, opts ...grpc.CallOption) (*ReceiveMQTTMessageRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveMQTTMessageRes)
	err := c.cc.Invoke(ctx, StreamEvent_ReceiveMQTTMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamEventClient) ReceiveWSMessage(ctx context.Context, in *ReceiveWSMessageReq, opts ...grpc.CallOption) (*ReceiveWSMessageRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveWSMessageRes)
	err := c.cc.Invoke(ctx, StreamEvent_ReceiveWSMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamEventClient) ReceiveKafkaMessage(ctx context.Context, in *ReceiveKafkaMessageReq, opts ...grpc.CallOption) (*ReceiveKafkaMessageRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveKafkaMessageRes)
	err := c.cc.Invoke(ctx, StreamEvent_ReceiveKafkaMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamEventClient) PushChunkAsdu(ctx context.Context, in *PushChunkAsduReq, opts ...grpc.CallOption) (*PushChunkAsduRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushChunkAsduRes)
	err := c.cc.Invoke(ctx, StreamEvent_PushChunkAsdu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamEventClient) UpSocketMessage(ctx context.Context, in *UpSocketMessageReq, opts ...grpc.CallOption) (*UpSocketMessageReq, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpSocketMessageReq)
	err := c.cc.Invoke(ctx, StreamEvent_UpSocketMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamEventClient) HandlerPlanTaskEvent(ctx context.Context, in *HandlerPlanTaskEventReq, opts ...grpc.CallOption) (*HandlerPlanTaskEventRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerPlanTaskEventRes)
	err := c.cc.Invoke(ctx, StreamEvent_HandlerPlanTaskEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamEventClient) NotifyPlanEvent(ctx context.Context, in *NotifyPlanEventReq, opts ...grpc.CallOption) (*NotifyPlanEventRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyPlanEventRes)
	err := c.cc.Invoke(ctx, StreamEvent_NotifyPlanEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamEventServer is the server API for StreamEvent service.
// All implementations must embed UnimplementedStreamEventServer
// for forward compatibility.
type StreamEventServer interface {
	// 接收MQTT消息
	ReceiveMQTTMessage(context.Context, *ReceiveMQTTMessageReq) (*ReceiveMQTTMessageRes, error)
	// 接收WS消息
	ReceiveWSMessage(context.Context, *ReceiveWSMessageReq) (*ReceiveWSMessageRes, error)
	// 接收kafka消息
	ReceiveKafkaMessage(context.Context, *ReceiveKafkaMessageReq) (*ReceiveKafkaMessageRes, error)
	// 推送 chunk asdu 104协议消息
	PushChunkAsdu(context.Context, *PushChunkAsduReq) (*PushChunkAsduRes, error)
	// 上行socket标准消息, 可以用于__up__和自定义up事件
	UpSocketMessage(context.Context, *UpSocketMessageReq) (*UpSocketMessageReq, error)
	// 计划任务事件处理
	HandlerPlanTaskEvent(context.Context, *HandlerPlanTaskEventReq) (*HandlerPlanTaskEventRes, error)
	// 通知计划任务事件
	NotifyPlanEvent(context.Context, *NotifyPlanEventReq) (*NotifyPlanEventRes, error)
	mustEmbedUnimplementedStreamEventServer()
}

// UnimplementedStreamEventServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamEventServer struct{}

func (UnimplementedStreamEventServer) ReceiveMQTTMessage(context.Context, *ReceiveMQTTMessageReq) (*ReceiveMQTTMessageRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMQTTMessage not implemented")
}
func (UnimplementedStreamEventServer) ReceiveWSMessage(context.Context, *ReceiveWSMessageReq) (*ReceiveWSMessageRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveWSMessage not implemented")
}
func (UnimplementedStreamEventServer) ReceiveKafkaMessage(context.Context, *ReceiveKafkaMessageReq) (*ReceiveKafkaMessageRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveKafkaMessage not implemented")
}
func (UnimplementedStreamEventServer) PushChunkAsdu(context.Context, *PushChunkAsduReq) (*PushChunkAsduRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushChunkAsdu not implemented")
}
func (UnimplementedStreamEventServer) UpSocketMessage(context.Context, *UpSocketMessageReq) (*UpSocketMessageReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpSocketMessage not implemented")
}
func (UnimplementedStreamEventServer) HandlerPlanTaskEvent(context.Context, *HandlerPlanTaskEventReq) (*HandlerPlanTaskEventRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlerPlanTaskEvent not implemented")
}
func (UnimplementedStreamEventServer) NotifyPlanEvent(context.Context, *NotifyPlanEventReq) (*NotifyPlanEventRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyPlanEvent not implemented")
}
func (UnimplementedStreamEventServer) mustEmbedUnimplementedStreamEventServer() {}
func (UnimplementedStreamEventServer) testEmbeddedByValue()                     {}

// UnsafeStreamEventServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamEventServer will
// result in compilation errors.
type UnsafeStreamEventServer interface {
	mustEmbedUnimplementedStreamEventServer()
}

func RegisterStreamEventServer(s grpc.ServiceRegistrar, srv StreamEventServer) {
	// If the following call pancis, it indicates UnimplementedStreamEventServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamEvent_ServiceDesc, srv)
}

func _StreamEvent_ReceiveMQTTMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveMQTTMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamEventServer).ReceiveMQTTMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamEvent_ReceiveMQTTMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamEventServer).ReceiveMQTTMessage(ctx, req.(*ReceiveMQTTMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamEvent_ReceiveWSMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveWSMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamEventServer).ReceiveWSMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamEvent_ReceiveWSMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamEventServer).ReceiveWSMessage(ctx, req.(*ReceiveWSMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamEvent_ReceiveKafkaMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveKafkaMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamEventServer).ReceiveKafkaMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamEvent_ReceiveKafkaMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamEventServer).ReceiveKafkaMessage(ctx, req.(*ReceiveKafkaMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamEvent_PushChunkAsdu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushChunkAsduReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamEventServer).PushChunkAsdu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamEvent_PushChunkAsdu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamEventServer).PushChunkAsdu(ctx, req.(*PushChunkAsduReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamEvent_UpSocketMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpSocketMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamEventServer).UpSocketMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamEvent_UpSocketMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamEventServer).UpSocketMessage(ctx, req.(*UpSocketMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamEvent_HandlerPlanTaskEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandlerPlanTaskEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamEventServer).HandlerPlanTaskEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamEvent_HandlerPlanTaskEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamEventServer).HandlerPlanTaskEvent(ctx, req.(*HandlerPlanTaskEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamEvent_NotifyPlanEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyPlanEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamEventServer).NotifyPlanEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamEvent_NotifyPlanEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamEventServer).NotifyPlanEvent(ctx, req.(*NotifyPlanEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamEvent_ServiceDesc is the grpc.ServiceDesc for StreamEvent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamEvent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streamevent.StreamEvent",
	HandlerType: (*StreamEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMQTTMessage",
			Handler:    _StreamEvent_ReceiveMQTTMessage_Handler,
		},
		{
			MethodName: "ReceiveWSMessage",
			Handler:    _StreamEvent_ReceiveWSMessage_Handler,
		},
		{
			MethodName: "ReceiveKafkaMessage",
			Handler:    _StreamEvent_ReceiveKafkaMessage_Handler,
		},
		{
			MethodName: "PushChunkAsdu",
			Handler:    _StreamEvent_PushChunkAsdu_Handler,
		},
		{
			MethodName: "UpSocketMessage",
			Handler:    _StreamEvent_UpSocketMessage_Handler,
		},
		{
			MethodName: "HandlerPlanTaskEvent",
			Handler:    _StreamEvent_HandlerPlanTaskEvent_Handler,
		},
		{
			MethodName: "NotifyPlanEvent",
			Handler:    _StreamEvent_NotifyPlanEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streamevent.proto",
}
