// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: ispagent.proto

package ispagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IspAgent_ExecuteCommand_FullMethodName              = "/ispagent.IspAgent/ExecuteCommand"
	IspAgent_SendPatrolDeviceRunData_FullMethodName     = "/ispagent.IspAgent/SendPatrolDeviceRunData"
	IspAgent_SendPatrolDeviceStatusData_FullMethodName  = "/ispagent.IspAgent/SendPatrolDeviceStatusData"
	IspAgent_SendPatrolDeviceCoordinates_FullMethodName = "/ispagent.IspAgent/SendPatrolDeviceCoordinates"
	IspAgent_ListTaskExecutions_FullMethodName          = "/ispagent.IspAgent/ListTaskExecutions"
	IspAgent_ListTaskConfigs_FullMethodName             = "/ispagent.IspAgent/ListTaskConfigs"
	IspAgent_TestFTPSUpload_FullMethodName              = "/ispagent.IspAgent/TestFTPSUpload"
	IspAgent_ListFTPSDirectory_FullMethodName           = "/ispagent.IspAgent/ListFTPSDirectory"
)

// IspAgentClient is the client API for IspAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IspAgentClient interface {
	// ExecuteCommand 通用指令透传（调用方指定 type/command）
	ExecuteCommand(ctx context.Context, in *CommandReq, opts ...grpc.CallOption) (*CommandRes, error)
	// SendPatrolDeviceRunData 巡视装置运行数据上报（表 J.34）
	SendPatrolDeviceRunData(ctx context.Context, in *SendPatrolDeviceRunDataReq, opts ...grpc.CallOption) (*CommandRes, error)
	// SendPatrolDeviceStatusData 巡视装置状态数据上报
	SendPatrolDeviceStatusData(ctx context.Context, in *SendPatrolDeviceStatusDataReq, opts ...grpc.CallOption) (*CommandRes, error)
	// SendPatrolDeviceCoordinates 巡视装置坐标上报（表 O.45）
	SendPatrolDeviceCoordinates(ctx context.Context, in *SendPatrolDeviceCoordinatesReq, opts ...grpc.CallOption) (*CommandRes, error)
	// ListTaskExecutions 查询任务未来执行时间（用于验证 rrule 配置）
	ListTaskExecutions(ctx context.Context, in *ListTaskExecutionsReq, opts ...grpc.CallOption) (*ListTaskExecutionsRes, error)
	// ListTaskConfigs 任务配置分页查询
	ListTaskConfigs(ctx context.Context, in *ListTaskConfigsReq, opts ...grpc.CallOption) (*ListTaskConfigsRes, error)
	// TestFTPSUpload 测试 FTPS 上传（上传 local/test.txt）
	TestFTPSUpload(ctx context.Context, in *TestFTPSUploadReq, opts ...grpc.CallOption) (*TestFTPSUploadRes, error)
	// ListFTPSDirectory 列出 FTPS 远程目录文件列表
	ListFTPSDirectory(ctx context.Context, in *ListFTPSDirectoryReq, opts ...grpc.CallOption) (*ListFTPSDirectoryRes, error)
}

type ispAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewIspAgentClient(cc grpc.ClientConnInterface) IspAgentClient {
	return &ispAgentClient{cc}
}

func (c *ispAgentClient) ExecuteCommand(ctx context.Context, in *CommandReq, opts ...grpc.CallOption) (*CommandRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandRes)
	err := c.cc.Invoke(ctx, IspAgent_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ispAgentClient) SendPatrolDeviceRunData(ctx context.Context, in *SendPatrolDeviceRunDataReq, opts ...grpc.CallOption) (*CommandRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandRes)
	err := c.cc.Invoke(ctx, IspAgent_SendPatrolDeviceRunData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ispAgentClient) SendPatrolDeviceStatusData(ctx context.Context, in *SendPatrolDeviceStatusDataReq, opts ...grpc.CallOption) (*CommandRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandRes)
	err := c.cc.Invoke(ctx, IspAgent_SendPatrolDeviceStatusData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ispAgentClient) SendPatrolDeviceCoordinates(ctx context.Context, in *SendPatrolDeviceCoordinatesReq, opts ...grpc.CallOption) (*CommandRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandRes)
	err := c.cc.Invoke(ctx, IspAgent_SendPatrolDeviceCoordinates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ispAgentClient) ListTaskExecutions(ctx context.Context, in *ListTaskExecutionsReq, opts ...grpc.CallOption) (*ListTaskExecutionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaskExecutionsRes)
	err := c.cc.Invoke(ctx, IspAgent_ListTaskExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ispAgentClient) ListTaskConfigs(ctx context.Context, in *ListTaskConfigsReq, opts ...grpc.CallOption) (*ListTaskConfigsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaskConfigsRes)
	err := c.cc.Invoke(ctx, IspAgent_ListTaskConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ispAgentClient) TestFTPSUpload(ctx context.Context, in *TestFTPSUploadReq, opts ...grpc.CallOption) (*TestFTPSUploadRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestFTPSUploadRes)
	err := c.cc.Invoke(ctx, IspAgent_TestFTPSUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ispAgentClient) ListFTPSDirectory(ctx context.Context, in *ListFTPSDirectoryReq, opts ...grpc.CallOption) (*ListFTPSDirectoryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFTPSDirectoryRes)
	err := c.cc.Invoke(ctx, IspAgent_ListFTPSDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IspAgentServer is the server API for IspAgent service.
// All implementations must embed UnimplementedIspAgentServer
// for forward compatibility.
type IspAgentServer interface {
	// ExecuteCommand 通用指令透传（调用方指定 type/command）
	ExecuteCommand(context.Context, *CommandReq) (*CommandRes, error)
	// SendPatrolDeviceRunData 巡视装置运行数据上报（表 J.34）
	SendPatrolDeviceRunData(context.Context, *SendPatrolDeviceRunDataReq) (*CommandRes, error)
	// SendPatrolDeviceStatusData 巡视装置状态数据上报
	SendPatrolDeviceStatusData(context.Context, *SendPatrolDeviceStatusDataReq) (*CommandRes, error)
	// SendPatrolDeviceCoordinates 巡视装置坐标上报（表 O.45）
	SendPatrolDeviceCoordinates(context.Context, *SendPatrolDeviceCoordinatesReq) (*CommandRes, error)
	// ListTaskExecutions 查询任务未来执行时间（用于验证 rrule 配置）
	ListTaskExecutions(context.Context, *ListTaskExecutionsReq) (*ListTaskExecutionsRes, error)
	// ListTaskConfigs 任务配置分页查询
	ListTaskConfigs(context.Context, *ListTaskConfigsReq) (*ListTaskConfigsRes, error)
	// TestFTPSUpload 测试 FTPS 上传（上传 local/test.txt）
	TestFTPSUpload(context.Context, *TestFTPSUploadReq) (*TestFTPSUploadRes, error)
	// ListFTPSDirectory 列出 FTPS 远程目录文件列表
	ListFTPSDirectory(context.Context, *ListFTPSDirectoryReq) (*ListFTPSDirectoryRes, error)
	mustEmbedUnimplementedIspAgentServer()
}

// UnimplementedIspAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIspAgentServer struct{}

func (UnimplementedIspAgentServer) ExecuteCommand(context.Context, *CommandReq) (*CommandRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedIspAgentServer) SendPatrolDeviceRunData(context.Context, *SendPatrolDeviceRunDataReq) (*CommandRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPatrolDeviceRunData not implemented")
}
func (UnimplementedIspAgentServer) SendPatrolDeviceStatusData(context.Context, *SendPatrolDeviceStatusDataReq) (*CommandRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPatrolDeviceStatusData not implemented")
}
func (UnimplementedIspAgentServer) SendPatrolDeviceCoordinates(context.Context, *SendPatrolDeviceCoordinatesReq) (*CommandRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPatrolDeviceCoordinates not implemented")
}
func (UnimplementedIspAgentServer) ListTaskExecutions(context.Context, *ListTaskExecutionsReq) (*ListTaskExecutionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaskExecutions not implemented")
}
func (UnimplementedIspAgentServer) ListTaskConfigs(context.Context, *ListTaskConfigsReq) (*ListTaskConfigsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaskConfigs not implemented")
}
func (UnimplementedIspAgentServer) TestFTPSUpload(context.Context, *TestFTPSUploadReq) (*TestFTPSUploadRes, error) {
	return nil, status.Error(codes.Unimplemented, "method TestFTPSUpload not implemented")
}
func (UnimplementedIspAgentServer) ListFTPSDirectory(context.Context, *ListFTPSDirectoryReq) (*ListFTPSDirectoryRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFTPSDirectory not implemented")
}
func (UnimplementedIspAgentServer) mustEmbedUnimplementedIspAgentServer() {}
func (UnimplementedIspAgentServer) testEmbeddedByValue()                  {}

// UnsafeIspAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IspAgentServer will
// result in compilation errors.
type UnsafeIspAgentServer interface {
	mustEmbedUnimplementedIspAgentServer()
}

func RegisterIspAgentServer(s grpc.ServiceRegistrar, srv IspAgentServer) {
	// If the following call panics, it indicates UnimplementedIspAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IspAgent_ServiceDesc, srv)
}

func _IspAgent_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IspAgentServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IspAgent_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IspAgentServer).ExecuteCommand(ctx, req.(*CommandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IspAgent_SendPatrolDeviceRunData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPatrolDeviceRunDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IspAgentServer).SendPatrolDeviceRunData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IspAgent_SendPatrolDeviceRunData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IspAgentServer).SendPatrolDeviceRunData(ctx, req.(*SendPatrolDeviceRunDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IspAgent_SendPatrolDeviceStatusData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPatrolDeviceStatusDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IspAgentServer).SendPatrolDeviceStatusData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IspAgent_SendPatrolDeviceStatusData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IspAgentServer).SendPatrolDeviceStatusData(ctx, req.(*SendPatrolDeviceStatusDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IspAgent_SendPatrolDeviceCoordinates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPatrolDeviceCoordinatesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IspAgentServer).SendPatrolDeviceCoordinates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IspAgent_SendPatrolDeviceCoordinates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IspAgentServer).SendPatrolDeviceCoordinates(ctx, req.(*SendPatrolDeviceCoordinatesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IspAgent_ListTaskExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskExecutionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IspAgentServer).ListTaskExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IspAgent_ListTaskExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IspAgentServer).ListTaskExecutions(ctx, req.(*ListTaskExecutionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IspAgent_ListTaskConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskConfigsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IspAgentServer).ListTaskConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IspAgent_ListTaskConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IspAgentServer).ListTaskConfigs(ctx, req.(*ListTaskConfigsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IspAgent_TestFTPSUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestFTPSUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IspAgentServer).TestFTPSUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IspAgent_TestFTPSUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IspAgentServer).TestFTPSUpload(ctx, req.(*TestFTPSUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IspAgent_ListFTPSDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFTPSDirectoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IspAgentServer).ListFTPSDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IspAgent_ListFTPSDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IspAgentServer).ListFTPSDirectory(ctx, req.(*ListFTPSDirectoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IspAgent_ServiceDesc is the grpc.ServiceDesc for IspAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IspAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ispagent.IspAgent",
	HandlerType: (*IspAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _IspAgent_ExecuteCommand_Handler,
		},
		{
			MethodName: "SendPatrolDeviceRunData",
			Handler:    _IspAgent_SendPatrolDeviceRunData_Handler,
		},
		{
			MethodName: "SendPatrolDeviceStatusData",
			Handler:    _IspAgent_SendPatrolDeviceStatusData_Handler,
		},
		{
			MethodName: "SendPatrolDeviceCoordinates",
			Handler:    _IspAgent_SendPatrolDeviceCoordinates_Handler,
		},
		{
			MethodName: "ListTaskExecutions",
			Handler:    _IspAgent_ListTaskExecutions_Handler,
		},
		{
			MethodName: "ListTaskConfigs",
			Handler:    _IspAgent_ListTaskConfigs_Handler,
		},
		{
			MethodName: "TestFTPSUpload",
			Handler:    _IspAgent_TestFTPSUpload_Handler,
		},
		{
			MethodName: "ListFTPSDirectory",
			Handler:    _IspAgent_ListFTPSDirectory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ispagent.proto",
}
