// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bridgekafka.proto

package bridgekafka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -------------------- 通用请求/响应 --------------------
type PublishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReq) Reset() {
	*x = PublishReq{}
	mi := &file_bridgekafka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReq) ProtoMessage() {}

func (x *PublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_bridgekafka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReq.ProtoReflect.Descriptor instead.
func (*PublishReq) Descriptor() ([]byte, []int) {
	return file_bridgekafka_proto_rawDescGZIP(), []int{0}
}

func (x *PublishReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublishReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PublishRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRes) Reset() {
	*x = PublishRes{}
	mi := &file_bridgekafka_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRes) ProtoMessage() {}

func (x *PublishRes) ProtoReflect() protoreflect.Message {
	mi := &file_bridgekafka_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRes.ProtoReflect.Descriptor instead.
func (*PublishRes) Descriptor() ([]byte, []int) {
	return file_bridgekafka_proto_rawDescGZIP(), []int{1}
}

var File_bridgekafka_proto protoreflect.FileDescriptor

const file_bridgekafka_proto_rawDesc = "" +
	"\n" +
	"\x11bridgekafka.proto\x12\vbridgekafka\"J\n" +
	"\n" +
	"PublishReq\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\f\n" +
	"\n" +
	"PublishRes2J\n" +
	"\vBridgeKafka\x12;\n" +
	"\aPublish\x12\x17.bridgekafka.PublishReq\x1a\x17.bridgekafka.PublishResB@\n" +
	"\x1bcom.github.bridgekafka.grpcB\x10BridgeKafkaProtoP\x01Z\r./bridgekafkab\x06proto3"

var (
	file_bridgekafka_proto_rawDescOnce sync.Once
	file_bridgekafka_proto_rawDescData []byte
)

func file_bridgekafka_proto_rawDescGZIP() []byte {
	file_bridgekafka_proto_rawDescOnce.Do(func() {
		file_bridgekafka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridgekafka_proto_rawDesc), len(file_bridgekafka_proto_rawDesc)))
	})
	return file_bridgekafka_proto_rawDescData
}

var file_bridgekafka_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bridgekafka_proto_goTypes = []any{
	(*PublishReq)(nil), // 0: bridgekafka.PublishReq
	(*PublishRes)(nil), // 1: bridgekafka.PublishRes
}
var file_bridgekafka_proto_depIdxs = []int32{
	0, // 0: bridgekafka.BridgeKafka.Publish:input_type -> bridgekafka.PublishReq
	1, // 1: bridgekafka.BridgeKafka.Publish:output_type -> bridgekafka.PublishRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bridgekafka_proto_init() }
func file_bridgekafka_proto_init() {
	if File_bridgekafka_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridgekafka_proto_rawDesc), len(file_bridgekafka_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridgekafka_proto_goTypes,
		DependencyIndexes: file_bridgekafka_proto_depIdxs,
		MessageInfos:      file_bridgekafka_proto_msgTypes,
	}.Build()
	File_bridgekafka_proto = out.File
	file_bridgekafka_proto_goTypes = nil
	file_bridgekafka_proto_depIdxs = nil
}
