CREATE TABLE IF NOT EXISTS `device_point_mapping` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `delete_time` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间（软删除标记）',
    `del_state` TINYINT NOT NULL DEFAULT 0 COMMENT '删除状态：0-未删除，1-已删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '版本号（乐观锁）',
    `tag_station` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '与 TDengine tag_station 对应',
    `coa` INT NOT NULL DEFAULT 0 COMMENT '与 TDengine coa 对应',
    `ioa` INT NOT NULL DEFAULT 0 COMMENT '与 TDengine ioa 对应',
    `device_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '设备编号/ID',
    `device_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '设备名称',
    `td_table_type` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'TDengine 表类型（遥信表/遥测表等，逗号分隔）',
    `enable_push` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许caller服务推送数据：0-不允许，1-允许',
    `enable_raw_insert` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许插入 raw 原生数据：0-否，1-是',
    `description` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '备注信息',
    `ext_1` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '扩展字段1，如：alarm, normal, control等，用于主题拆分',
    `ext_2` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '扩展字段2',
    `ext_3` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '扩展字段3',
    `ext_4` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '扩展字段4',
    `ext_5` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '扩展字段5',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_station_coa_ioa` (`tag_station`, `coa`, `ioa`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备与 IEC104 点位映射表';

-- 计划任务表
CREATE TABLE IF NOT EXISTS `plan` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `delete_time` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间（软删除标记）',
    `del_state` TINYINT NOT NULL DEFAULT 0 COMMENT '删除状态：0-未删除，1-已删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '版本号（乐观锁）',
    `plan_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '计划唯一标识',
    `plan_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '计划任务名称',
    `type` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '任务类型',
    `group_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '计划组ID,用于分组管理计划任务',
    `recurrence_rule` JSON NOT NULL COMMENT '重复规则，JSON格式存储',
    `start_time` DATETIME NOT NULL COMMENT '规则生效开始时间',
    `end_time` DATETIME NOT NULL COMMENT '规则生效结束时间',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-禁用，1-启用，2-已终止，3-暂停',
    `is_terminated` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已终止：0-未终止，1-已终止',
    `is_paused` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已暂停：0-未暂停，1-已暂停',
    `terminated_time` DATETIME NULL DEFAULT NULL COMMENT '终止时间',
    `terminated_reason` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '终止原因',
    `paused_time` DATETIME NULL DEFAULT NULL COMMENT '暂停时间',
    `paused_reason` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '暂停原因',
    `description` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '备注信息',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_plan_id` (`plan_id`),
    KEY `idx_type` (`type`),
    KEY `idx_group_id` (`group_id`),
    KEY `idx_status` (`status`),
    KEY `idx_start_time` (`start_time`),
    KEY `idx_end_time` (`end_time`),
    KEY `idx_is_terminated` (`is_terminated`),
    KEY `idx_terminated_time` (`terminated_time`),
    KEY `idx_is_paused` (`is_paused`),
    KEY `idx_paused_time` (`paused_time`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划任务表';

-- 计划执行项表
CREATE TABLE IF NOT EXISTS `plan_exec_item` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `delete_time` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间（软删除标记）',
    `del_state` TINYINT NOT NULL DEFAULT 0 COMMENT '删除状态：0-未删除，1-已删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '版本号（乐观锁）',
    `plan_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '关联的计划ID',
    `item_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '执行项ID',
    `item_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '执行项名称',
    `service_addr` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '业务服务地址',
    `payload` TEXT NOT NULL COMMENT '业务负载',
    `request_timeout` INT NOT NULL DEFAULT 0 COMMENT '请求超时时间（毫秒）',
    `plan_trigger_time` DATETIME NOT NULL COMMENT '计划触发时间',
    `next_trigger_time` DATETIME NOT NULL COMMENT '下次触发时间（扫表核心字段）',
    `last_trigger_time` DATETIME NULL DEFAULT NULL COMMENT '上次触发时间',
    `trigger_count` INT NOT NULL DEFAULT 0 COMMENT '触发次数',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-待执行，1-执行中，2-完成，3-失败，4-延期，5-已终止，6-暂停',
    `last_result` TEXT NOT NULL COMMENT '上次执行结果',
    `last_msg` TEXT NOT NULL COMMENT '上次执行消息',
    `is_terminated` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已终止：0-未终止，1-已终止',
    `terminated_time` DATETIME NULL DEFAULT NULL COMMENT '终止时间',
    `terminated_reason` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '终止原因',
    `is_paused` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已暂停：0-未暂停，1-已暂停',
    `paused_time` DATETIME NULL DEFAULT NULL COMMENT '暂停时间',
    `paused_reason` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '暂停原因',
    PRIMARY KEY (`id`),
    KEY `idx_plan_id` (`plan_id`),
    KEY `idx_item_id` (`item_id`),
    KEY `idx_next_trigger_time` (`next_trigger_time`),
    KEY `idx_status` (`status`),
    KEY `idx_last_trigger_time` (`last_trigger_time`),
    KEY `idx_is_terminated` (`is_terminated`),
    KEY `idx_terminated_time` (`terminated_time`),
    KEY `idx_is_paused` (`is_paused`),
    KEY `idx_paused_time` (`paused_time`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划执行项表';

-- 计划任务执行日志表
CREATE TABLE IF NOT EXISTS `plan_exec_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `delete_time` TIMESTAMP NULL DEFAULT NULL COMMENT '删除时间（软删除标记）',
    `del_state` TINYINT NOT NULL DEFAULT 0 COMMENT '删除状态：0-未删除，1-已删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '版本号（乐观锁）',
    `plan_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '计划任务ID',
    `plan_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '计划任务名称',
    `item_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '执行项ID',
    `item_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '执行项名称',
    `trigger_time` DATETIME NOT NULL COMMENT '触发时间',
    `trace_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '唯一追踪ID',
    `exec_result` TINYINT NOT NULL DEFAULT 0 COMMENT '执行结果：1-成功，2-失败，3-延期',
    `message` TEXT NOT NULL COMMENT '结果描述',
    PRIMARY KEY (`id`),
    KEY `idx_plan_id` (`plan_id`),
    KEY `idx_item_id` (`item_id`),
    KEY `idx_trigger_time` (`trigger_time`),
    KEY `idx_trace_id` (`trace_id`),
    KEY `idx_exec_result` (`exec_result`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划任务执行日志表';