CREATE TABLE IF NOT EXISTS `device_point_mapping` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
    `create_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `update_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    `delete_time` DATETIME(6) NULL DEFAULT NULL COMMENT '删除时间（软删除标记）',
    `del_state` TINYINT NOT NULL DEFAULT 0 COMMENT '删除状态：0-未删除，1-已删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '版本号（乐观锁）',
    `create_user` VARCHAR(64) DEFAULT '' COMMENT '创建人',
    `update_user` VARCHAR(64) DEFAULT '' COMMENT '更新人',
    `dept_code` VARCHAR(64) DEFAULT '' COMMENT '机构code',
    `tag_station` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '与 TDengine tag_station 对应',
    `coa` INT NOT NULL DEFAULT 0 COMMENT '与 TDengine coa 对应',
    `ioa` INT NOT NULL DEFAULT 0 COMMENT '与 TDengine ioa 对应',
    `device_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '设备编号/ID',
    `device_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '设备名称',
    `td_table_type` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'TDengine 表类型（遥信表/遥测表等，逗号分隔）',
    `enable_push` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许caller服务推送数据：0-不允许，1-允许',
    `enable_raw_insert` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许插入 raw 原生数据：0-否，1-是',
    `description` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '备注信息',
    `ext_1` VARCHAR(64) DEFAULT '' COMMENT '扩展字段1，如：alarm, normal, control等，用于主题拆分',
    `ext_2` VARCHAR(64) DEFAULT '' COMMENT '扩展字段2',
    `ext_3` VARCHAR(64) DEFAULT '' COMMENT '扩展字段3',
    `ext_4` VARCHAR(64) DEFAULT '' COMMENT '扩展字段4',
    `ext_5` VARCHAR(64) DEFAULT '' COMMENT '扩展字段5',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_station_coa_ioa` (`tag_station`, `coa`, `ioa`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备与 IEC104 点位映射表';

-- 计划任务表
CREATE TABLE IF NOT EXISTS `plan` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
    `create_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `update_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    `delete_time` DATETIME(6) NULL DEFAULT NULL COMMENT '删除时间（软删除标记）',
    `del_state` TINYINT NOT NULL DEFAULT 0 COMMENT '删除状态：0-未删除，1-已删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '版本号（乐观锁）',
    `create_user` VARCHAR(64) DEFAULT '' COMMENT '创建人',
    `update_user` VARCHAR(64) DEFAULT '' COMMENT '更新人',
    `dept_code` VARCHAR(64) DEFAULT '' COMMENT '机构code',
    `plan_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '计划唯一标识',
    `plan_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '计划任务名称',
    `type` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '任务类型',
    `group_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '计划组ID,用于分组管理计划任务',
    `recurrence_rule` JSON NOT NULL COMMENT '重复规则，JSON格式存储',
    `start_time` DATETIME(6) NOT NULL COMMENT '规则生效开始时间',
    `end_time` DATETIME(6) NOT NULL COMMENT '规则生效结束时间',
    `status` INT NOT NULL DEFAULT 0 COMMENT '状态：0-禁用，1-启用，2-暂停，3-终止',
    `terminated_reason` VARCHAR(256) DEFAULT '' COMMENT '终止原因',
    `paused_time` DATETIME(6) DEFAULT NULL COMMENT '暂停时间',
    `paused_reason` VARCHAR(256) DEFAULT '' COMMENT '暂停原因',
    `finished_time` DATETIME(6) NULL COMMENT '结束时间',
    `description` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '备注信息',
    `ext_1` VARCHAR(64) DEFAULT '' COMMENT '扩展字段1',
    `ext_2` VARCHAR(64) DEFAULT '' COMMENT '扩展字段2',
    `ext_3` VARCHAR(64) DEFAULT '' COMMENT '扩展字段3',
    `ext_4` VARCHAR(64) DEFAULT '' COMMENT '扩展字段4',
    `ext_5` VARCHAR(64) DEFAULT '' COMMENT '扩展字段5',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_plan_id` (`plan_id`),
    KEY `idx_type` (`type`),
    KEY `idx_group_id` (`group_id`),
    KEY `idx_status` (`status`),
    KEY `idx_start_time` (`start_time`),
    KEY `idx_end_time` (`end_time`),
    KEY `idx_paused_time` (`paused_time`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划任务表';

-- 计划执行项表
CREATE TABLE IF NOT EXISTS `plan_exec_item` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
    `create_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `update_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    `delete_time` DATETIME(6) NULL DEFAULT NULL COMMENT '删除时间（软删除标记）',
    `del_state` TINYINT NOT NULL DEFAULT 0 COMMENT '删除状态：0-未删除，1-已删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '版本号（乐观锁）',
    `create_user` VARCHAR(64) DEFAULT '' COMMENT '创建人',
    `update_user` VARCHAR(64) DEFAULT '' COMMENT '更新人',
    `dept_code` VARCHAR(64) DEFAULT '' COMMENT '机构code',
    `plan_pk` BIGINT NOT NULL DEFAULT 0 COMMENT '关联的计划主键ID',
    `plan_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '关联的计划ID',
    `batch_pk` BIGINT NOT NULL DEFAULT 0 COMMENT '批主键ID',
    `batch_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '批ID',
    `exec_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '执行ID',
    `item_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '执行项ID',
    `item_type` VARCHAR(64) DEFAULT '' COMMENT '执行项类型',
    `item_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '执行项名称',
    `item_row_id` BIGINT NOT NULL DEFAULT 0 COMMENT '执行项行ID',
    `point_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '点位id',
    `payload` TEXT NOT NULL COMMENT '业务负载',
    `request_timeout` INT NOT NULL DEFAULT 0 COMMENT '请求超时时间（毫秒）',
    `plan_trigger_time` DATETIME(6) NOT NULL COMMENT '计划触发时间',
    `next_trigger_time` DATETIME(6) NOT NULL COMMENT '下次触发时间（扫表核心字段）',
    `last_trigger_time` DATETIME(6) NULL DEFAULT NULL COMMENT '上次触发时间',
    `trigger_count` INT NOT NULL DEFAULT 0 COMMENT '触发次数',
    `status` INT NOT NULL DEFAULT 0 COMMENT '状态：0-等待调度，10-延期等待，100-执行中，150-暂停，200-完成，300-终止',
    `last_result` varchar(2000) DEFAULT '' COMMENT '上次执行结果',
    `last_message` varchar(2000) DEFAULT '' COMMENT '上次结果描述',
    `last_reason` TEXT COMMENT '上次结果原因',
    `terminated_reason` VARCHAR(256) DEFAULT '' COMMENT '终止原因',
    `paused_time` DATETIME(6) DEFAULT NULL COMMENT '暂停时间',
    `paused_reason` VARCHAR(256) DEFAULT '' COMMENT '暂停原因',
    `ext_1` VARCHAR(64) DEFAULT '' COMMENT '扩展字段1',
    `ext_2` VARCHAR(64) DEFAULT '' COMMENT '扩展字段2',
    `ext_3` VARCHAR(64) DEFAULT '' COMMENT '扩展字段3',
    `ext_4` VARCHAR(64) DEFAULT '' COMMENT '扩展字段4',
    `ext_5` VARCHAR(64) DEFAULT '' COMMENT '扩展字段5',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_exec_id` (`exec_id`),
    KEY `idx_batch_pk` (`batch_pk`),
    KEY `idx_batch_id` (`batch_id`),
    KEY `idx_plan_pk_item_id` (`plan_pk`, `item_id`),
    KEY `idx_plan_id_item_id` (`plan_id`, `item_id`),
    KEY `idx_point_id` (`point_id`),
    KEY `idx_status` (`status`),
    KEY `idx_core_scan` (`del_state`, `next_trigger_time`, `status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划执行项表';

-- 计划批次表
CREATE TABLE IF NOT EXISTS `plan_batch` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
    `create_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `update_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    `delete_time` DATETIME(6) NULL DEFAULT NULL COMMENT '删除时间（软删除标记）',
    `del_state` TINYINT NOT NULL DEFAULT 0 COMMENT '删除状态：0-未删除，1-已删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '版本号（乐观锁）',
    `create_user` VARCHAR(64) DEFAULT '' COMMENT '创建人',
    `update_user` VARCHAR(64) DEFAULT '' COMMENT '更新人',
    `dept_code` VARCHAR(64) DEFAULT '' COMMENT '机构code',
    `plan_pk` BIGINT NOT NULL DEFAULT 0 COMMENT '关联的计划主键ID',
    `plan_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '关联的计划ID',
    `batch_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '批ID',
    `batch_name` VARCHAR(128) DEFAULT '' COMMENT '批次名称',
    `batch_num` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '批次序号',
    `status` INT NOT NULL DEFAULT 0 COMMENT '状态：0-禁用，1-启用，2-暂停，3-终止',
    `plan_trigger_time` DATETIME(6) NULL COMMENT'计划触发时间',
    `terminated_reason` VARCHAR(256) DEFAULT '' COMMENT '终止原因',
    `paused_time` DATETIME(6) NULL DEFAULT NULL COMMENT '暂停时间',
    `paused_reason` VARCHAR(256) DEFAULT '' COMMENT '暂停原因',
    `finished_time` DATETIME(6) NULL COMMENT '结束时间',
    `ext_1` VARCHAR(64) DEFAULT '' COMMENT '扩展字段1',
    `ext_2` VARCHAR(64) DEFAULT '' COMMENT '扩展字段2',
    `ext_3` VARCHAR(64) DEFAULT '' COMMENT '扩展字段3',
    `ext_4` VARCHAR(64) DEFAULT '' COMMENT '扩展字段4',
    `ext_5` VARCHAR(64) DEFAULT '' COMMENT '扩展字段5',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_batch_id` (`batch_id`),
    UNIQUE KEY `uk_batch_num` (`batch_num`),
    KEY `idx_plan_id` (`plan_id`),
    KEY `idx_plan_pk` (`plan_pk`),
    KEY `idx_status` (`status`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划批次表';

-- 计划任务执行日志表
CREATE TABLE IF NOT EXISTS `plan_exec_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
    `create_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
    `update_time` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
    `delete_time` DATETIME(6) NULL DEFAULT NULL COMMENT '删除时间（软删除标记）',
    `del_state` TINYINT NOT NULL DEFAULT 0 COMMENT '删除状态：0-未删除，1-已删除',
    `version` INT NOT NULL DEFAULT 0 COMMENT '版本号（乐观锁）',
    `create_user` VARCHAR(64) DEFAULT '' COMMENT '创建人',
    `update_user` VARCHAR(64) DEFAULT '' COMMENT '更新人',
    `dept_code` VARCHAR(64) DEFAULT '' COMMENT '机构code',
    `plan_pk` BIGINT NOT NULL DEFAULT 0 COMMENT '关联的计划主键ID',
    `plan_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '计划任务ID',
    `plan_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '计划任务名称',
    `batch_pk` BIGINT NOT NULL DEFAULT 0 COMMENT '批主键ID',
    `batch_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '批ID',
    `item_pk` BIGINT NOT NULL DEFAULT 0 COMMENT '关联的执行项主键ID',
    `exec_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '执行ID',
    `item_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '执行项ID',
    `item_type` VARCHAR(64) DEFAULT '' COMMENT '执行项类型',
    `item_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '执行项名称',
    `point_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '点位id',
    `trigger_time` DATETIME(6) NOT NULL COMMENT '触发时间',
    `trace_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '唯一追踪ID',
    `exec_result` varchar(2000) NOT NULL DEFAULT '' COMMENT '执行结果',
    `message` varchar(2000) DEFAULT '' COMMENT '结果描述',
    `reason` TEXT COMMENT '结果原因',
    PRIMARY KEY (`id`),
    KEY `idx_plan_pk` (`plan_pk`),
    KEY `idx_plan_id` (`plan_id`),
    KEY `idx_batch_pk` (`batch_pk`),
    KEY `idx_batch_id` (`batch_id`),
    KEY `idx_item_pk` (`item_pk`),
    KEY `idx_exec_id` (`exec_id`),
    KEY `idx_item_id` (`item_id`),
    KEY `idx_trigger_time` (`trigger_time`),
    KEY `idx_trace_id` (`trace_id`),
    KEY `idx_exec_result` (`exec_result`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='计划任务执行日志表';