syntax = "proto3";
package bridgedump;
option go_package = "./bridgedump";


message Req {
  string ping = 1 [json_name = "ping"];
}

message Res {
  string pong = 1 [json_name = "pong"];
}

message CableWorkListReq {
  repeated DeviceRunData data = 1 [json_name = "data"];
}

message CableWorkListRes {
  int32 code = 1 [json_name = "code"];
  string msg = 2 [json_name = "msg"];
}

// 设备运行数据单条记录
message DeviceRunData {
  // 设备ID
  string dtu_id = 1 [json_name = "dtuId"];
  // 电流值
  double load_cur = 2 [json_name = "loadCur"];
  // 电压值
  double load_voltage = 3 [json_name = "loadVoltage"];
  // 相别（1：A相，2：B相，3：C相）
  int32 sltype = 4 [json_name = "sltype"];
  // 工况时间，格式：yyyyMMddHHmmss
  string operate_time = 5 [json_name = "operateTime"];
  // 环境温度
  double am_temperature = 6 [json_name = "amTemperature"];
  // GPS有效性(1:有效 0:无效)
  int32 gps = 7 [json_name = "gps"];

  // 工况时间 CableWorkListData -> operateTime
  string work_time = 8 [json_name = "workTime"];
}

message CableFaultReq{
  // 多条故障结果数据
  repeated FaultData data = 1 [json_name = "data"];
}

message CableFaultRes{
  int32 code = 1 [json_name = "code"];
  string msg = 2 [json_name = "msg"];
}

// 单条故障结果数据
message FaultData {
  // 故障编号(唯一)
  string acci_id = 1 [json_name = "acciId"];
  // 故障时间，格式：yyyyMMddHHmmssSSS
  string down_time = 2 [json_name = "downTime"];
  // 故障线路名称
  string ml_name = 3 [json_name = "mlName"];
  // 区间标识(0:精确定位 1: 区间定位)
  int32 fixed_type = 4 [json_name = "fixedType"];
  // 故障起始杆塔
  string diaElepo1 = 5 [json_name = "diaElepo1"];
  // 故障终止杆塔
  string diaElepo2 = 6 [json_name = "diaElepo2"];
  // 故障杆塔
  string dia_elepo = 7 [json_name = "diaElepo"];
  // 故障距离（米）
  double err_distance = 8 [json_name = "errDistance"];
  // 故障相别（1，2,3代表A,B,C三相)
  int32 fsltype = 9 [json_name = "fsltype"];
  // 故障描述
  string notice = 10 [json_name = "notice"];
  // 告警处理状态（0：未处理  1：已处理）
  int32 warn_processed = 11 [json_name = "warnProcessed"];
  // 故障类型(SC短路 GD接地 OT其他)
  string warn_category = 12 [json_name = "warnCategory"];

  // 故障时间 -> downTime
  string acci_time = 13 [json_name = "acciTime"];
  // 告警类别
  string short_type = 14 [json_name = "shortType"];
}

message CableFaultWaveReq{
  // 多条故障波形数据
  repeated FaultWaveData data = 1 [json_name = "data"];
}

message CableFaultWaveRes{
  int32 code = 1 [json_name = "code"];
  string msg = 2 [json_name = "msg"];
}

// 单条故障波形数据
message FaultWaveData {
  // 故障编号（唯一）
  string acci_id = 1 [json_name = "acciId"];
  // 波形编号（唯一）
  string wave_batch_id = 2 [json_name = "waveBatchId"];
  // 设备ID(终端编号)
  string dtu_id = 3 [json_name = "dtuId"];
  // 波形类型（1：代表行波，3：代表工频）
  int32 wave_type = 4 [json_name = "waveType"];
  // 波形起始时间(精确到纳秒)
  string ahead_time = 5 [json_name = "aheadTime"];
  // 波形数据(英文逗号分隔)
  string wave_data = 6 [json_name = "waveData"];
  // 采样率
  int32 samprate = 7 [json_name = "samprate"];
}

service BridgeDumpRpc {
  rpc Ping (Req) returns (Res);

  // 电缆设备运行数据接入
  rpc CableWorkList(CableWorkListReq) returns (CableWorkListRes);
  // 电缆故障结果数据接入
  rpc CableFault(CableFaultReq) returns (CableFaultRes);
  // 电缆故障波形数据接入
  rpc CableFaultWave(CableFaultWaveReq) returns (CableFaultWaveRes);
}