// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: socketpush.proto

package socketpush

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocketPush_GenToken_FullMethodName           = "/socketpush.SocketPush/GenToken"
	SocketPush_JoinRoom_FullMethodName           = "/socketpush.SocketPush/JoinRoom"
	SocketPush_LeaveRoom_FullMethodName          = "/socketpush.SocketPush/LeaveRoom"
	SocketPush_BroadcastRoom_FullMethodName      = "/socketpush.SocketPush/BroadcastRoom"
	SocketPush_BroadcastGlobal_FullMethodName    = "/socketpush.SocketPush/BroadcastGlobal"
	SocketPush_KickSession_FullMethodName        = "/socketpush.SocketPush/KickSession"
	SocketPush_KickMetaSession_FullMethodName    = "/socketpush.SocketPush/KickMetaSession"
	SocketPush_SendToSession_FullMethodName      = "/socketpush.SocketPush/SendToSession"
	SocketPush_SendToSessions_FullMethodName     = "/socketpush.SocketPush/SendToSessions"
	SocketPush_SendToMetaSession_FullMethodName  = "/socketpush.SocketPush/SendToMetaSession"
	SocketPush_SendToMetaSessions_FullMethodName = "/socketpush.SocketPush/SendToMetaSessions"
	SocketPush_SocketGtwStat_FullMethodName      = "/socketpush.SocketPush/SocketGtwStat"
)

// SocketPushClient is the client API for SocketPush service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocketPushClient interface {
	// 生成token
	GenToken(ctx context.Context, in *GenTokenReq, opts ...grpc.CallOption) (*GenTokenRes, error)
	// 加入房间
	JoinRoom(ctx context.Context, in *JoinRoomReq, opts ...grpc.CallOption) (*JoinRoomRes, error)
	// 离开房间
	LeaveRoom(ctx context.Context, in *LeaveRoomReq, opts ...grpc.CallOption) (*LeaveRoomRes, error)
	// 向指定房间广播消息
	BroadcastRoom(ctx context.Context, in *BroadcastRoomReq, opts ...grpc.CallOption) (*BroadcastRoomRes, error)
	// 向所有在线前端广播消息
	BroadcastGlobal(ctx context.Context, in *BroadcastGlobalReq, opts ...grpc.CallOption) (*BroadcastGlobalRes, error)
	// 剔除 session
	KickSession(ctx context.Context, in *KickSessionReq, opts ...grpc.CallOption) (*KickSessionRes, error)
	// 指定元数据剔除 session
	KickMetaSession(ctx context.Context, in *KickMetaSessionReq, opts ...grpc.CallOption) (*KickMetaSessionRes, error)
	// 向指定 session 发送消息
	SendToSession(ctx context.Context, in *SendToSessionReq, opts ...grpc.CallOption) (*SendToSessionRes, error)
	// 向指定 session 批量发送消息
	SendToSessions(ctx context.Context, in *SendToSessionsReq, opts ...grpc.CallOption) (*SendToSessionsRes, error)
	// 向指定元数据 session 发送消息
	SendToMetaSession(ctx context.Context, in *SendToMetaSessionReq, opts ...grpc.CallOption) (*SendToMetaSessionRes, error)
	// 向指定元数据 session 批量发送消息
	SendToMetaSessions(ctx context.Context, in *SendToMetaSessionsReq, opts ...grpc.CallOption) (*SendToMetaSessionsRes, error)
	// 获取网关统计信息
	SocketGtwStat(ctx context.Context, in *SocketGtwStatReq, opts ...grpc.CallOption) (*SocketGtwStatRes, error)
}

type socketPushClient struct {
	cc grpc.ClientConnInterface
}

func NewSocketPushClient(cc grpc.ClientConnInterface) SocketPushClient {
	return &socketPushClient{cc}
}

func (c *socketPushClient) GenToken(ctx context.Context, in *GenTokenReq, opts ...grpc.CallOption) (*GenTokenRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenTokenRes)
	err := c.cc.Invoke(ctx, SocketPush_GenToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) JoinRoom(ctx context.Context, in *JoinRoomReq, opts ...grpc.CallOption) (*JoinRoomRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinRoomRes)
	err := c.cc.Invoke(ctx, SocketPush_JoinRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) LeaveRoom(ctx context.Context, in *LeaveRoomReq, opts ...grpc.CallOption) (*LeaveRoomRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveRoomRes)
	err := c.cc.Invoke(ctx, SocketPush_LeaveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) BroadcastRoom(ctx context.Context, in *BroadcastRoomReq, opts ...grpc.CallOption) (*BroadcastRoomRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastRoomRes)
	err := c.cc.Invoke(ctx, SocketPush_BroadcastRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) BroadcastGlobal(ctx context.Context, in *BroadcastGlobalReq, opts ...grpc.CallOption) (*BroadcastGlobalRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastGlobalRes)
	err := c.cc.Invoke(ctx, SocketPush_BroadcastGlobal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) KickSession(ctx context.Context, in *KickSessionReq, opts ...grpc.CallOption) (*KickSessionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickSessionRes)
	err := c.cc.Invoke(ctx, SocketPush_KickSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) KickMetaSession(ctx context.Context, in *KickMetaSessionReq, opts ...grpc.CallOption) (*KickMetaSessionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickMetaSessionRes)
	err := c.cc.Invoke(ctx, SocketPush_KickMetaSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) SendToSession(ctx context.Context, in *SendToSessionReq, opts ...grpc.CallOption) (*SendToSessionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToSessionRes)
	err := c.cc.Invoke(ctx, SocketPush_SendToSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) SendToSessions(ctx context.Context, in *SendToSessionsReq, opts ...grpc.CallOption) (*SendToSessionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToSessionsRes)
	err := c.cc.Invoke(ctx, SocketPush_SendToSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) SendToMetaSession(ctx context.Context, in *SendToMetaSessionReq, opts ...grpc.CallOption) (*SendToMetaSessionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToMetaSessionRes)
	err := c.cc.Invoke(ctx, SocketPush_SendToMetaSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) SendToMetaSessions(ctx context.Context, in *SendToMetaSessionsReq, opts ...grpc.CallOption) (*SendToMetaSessionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToMetaSessionsRes)
	err := c.cc.Invoke(ctx, SocketPush_SendToMetaSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketPushClient) SocketGtwStat(ctx context.Context, in *SocketGtwStatReq, opts ...grpc.CallOption) (*SocketGtwStatRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SocketGtwStatRes)
	err := c.cc.Invoke(ctx, SocketPush_SocketGtwStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocketPushServer is the server API for SocketPush service.
// All implementations must embed UnimplementedSocketPushServer
// for forward compatibility.
type SocketPushServer interface {
	// 生成token
	GenToken(context.Context, *GenTokenReq) (*GenTokenRes, error)
	// 加入房间
	JoinRoom(context.Context, *JoinRoomReq) (*JoinRoomRes, error)
	// 离开房间
	LeaveRoom(context.Context, *LeaveRoomReq) (*LeaveRoomRes, error)
	// 向指定房间广播消息
	BroadcastRoom(context.Context, *BroadcastRoomReq) (*BroadcastRoomRes, error)
	// 向所有在线前端广播消息
	BroadcastGlobal(context.Context, *BroadcastGlobalReq) (*BroadcastGlobalRes, error)
	// 剔除 session
	KickSession(context.Context, *KickSessionReq) (*KickSessionRes, error)
	// 指定元数据剔除 session
	KickMetaSession(context.Context, *KickMetaSessionReq) (*KickMetaSessionRes, error)
	// 向指定 session 发送消息
	SendToSession(context.Context, *SendToSessionReq) (*SendToSessionRes, error)
	// 向指定 session 批量发送消息
	SendToSessions(context.Context, *SendToSessionsReq) (*SendToSessionsRes, error)
	// 向指定元数据 session 发送消息
	SendToMetaSession(context.Context, *SendToMetaSessionReq) (*SendToMetaSessionRes, error)
	// 向指定元数据 session 批量发送消息
	SendToMetaSessions(context.Context, *SendToMetaSessionsReq) (*SendToMetaSessionsRes, error)
	// 获取网关统计信息
	SocketGtwStat(context.Context, *SocketGtwStatReq) (*SocketGtwStatRes, error)
	mustEmbedUnimplementedSocketPushServer()
}

// UnimplementedSocketPushServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocketPushServer struct{}

func (UnimplementedSocketPushServer) GenToken(context.Context, *GenTokenReq) (*GenTokenRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenToken not implemented")
}
func (UnimplementedSocketPushServer) JoinRoom(context.Context, *JoinRoomReq) (*JoinRoomRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}
func (UnimplementedSocketPushServer) LeaveRoom(context.Context, *LeaveRoomReq) (*LeaveRoomRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveRoom not implemented")
}
func (UnimplementedSocketPushServer) BroadcastRoom(context.Context, *BroadcastRoomReq) (*BroadcastRoomRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastRoom not implemented")
}
func (UnimplementedSocketPushServer) BroadcastGlobal(context.Context, *BroadcastGlobalReq) (*BroadcastGlobalRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastGlobal not implemented")
}
func (UnimplementedSocketPushServer) KickSession(context.Context, *KickSessionReq) (*KickSessionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickSession not implemented")
}
func (UnimplementedSocketPushServer) KickMetaSession(context.Context, *KickMetaSessionReq) (*KickMetaSessionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickMetaSession not implemented")
}
func (UnimplementedSocketPushServer) SendToSession(context.Context, *SendToSessionReq) (*SendToSessionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToSession not implemented")
}
func (UnimplementedSocketPushServer) SendToSessions(context.Context, *SendToSessionsReq) (*SendToSessionsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToSessions not implemented")
}
func (UnimplementedSocketPushServer) SendToMetaSession(context.Context, *SendToMetaSessionReq) (*SendToMetaSessionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToMetaSession not implemented")
}
func (UnimplementedSocketPushServer) SendToMetaSessions(context.Context, *SendToMetaSessionsReq) (*SendToMetaSessionsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToMetaSessions not implemented")
}
func (UnimplementedSocketPushServer) SocketGtwStat(context.Context, *SocketGtwStatReq) (*SocketGtwStatRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SocketGtwStat not implemented")
}
func (UnimplementedSocketPushServer) mustEmbedUnimplementedSocketPushServer() {}
func (UnimplementedSocketPushServer) testEmbeddedByValue()                    {}

// UnsafeSocketPushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocketPushServer will
// result in compilation errors.
type UnsafeSocketPushServer interface {
	mustEmbedUnimplementedSocketPushServer()
}

func RegisterSocketPushServer(s grpc.ServiceRegistrar, srv SocketPushServer) {
	// If the following call pancis, it indicates UnimplementedSocketPushServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocketPush_ServiceDesc, srv)
}

func _SocketPush_GenToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).GenToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_GenToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).GenToken(ctx, req.(*GenTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_JoinRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).JoinRoom(ctx, req.(*JoinRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_LeaveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).LeaveRoom(ctx, req.(*LeaveRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_BroadcastRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).BroadcastRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_BroadcastRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).BroadcastRoom(ctx, req.(*BroadcastRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_BroadcastGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastGlobalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).BroadcastGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_BroadcastGlobal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).BroadcastGlobal(ctx, req.(*BroadcastGlobalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_KickSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).KickSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_KickSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).KickSession(ctx, req.(*KickSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_KickMetaSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickMetaSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).KickMetaSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_KickMetaSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).KickMetaSession(ctx, req.(*KickMetaSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_SendToSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).SendToSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_SendToSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).SendToSession(ctx, req.(*SendToSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_SendToSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).SendToSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_SendToSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).SendToSessions(ctx, req.(*SendToSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_SendToMetaSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToMetaSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).SendToMetaSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_SendToMetaSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).SendToMetaSession(ctx, req.(*SendToMetaSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_SendToMetaSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToMetaSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).SendToMetaSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_SendToMetaSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).SendToMetaSessions(ctx, req.(*SendToMetaSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketPush_SocketGtwStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketGtwStatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketPushServer).SocketGtwStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketPush_SocketGtwStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketPushServer).SocketGtwStat(ctx, req.(*SocketGtwStatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SocketPush_ServiceDesc is the grpc.ServiceDesc for SocketPush service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocketPush_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "socketpush.SocketPush",
	HandlerType: (*SocketPushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenToken",
			Handler:    _SocketPush_GenToken_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _SocketPush_JoinRoom_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _SocketPush_LeaveRoom_Handler,
		},
		{
			MethodName: "BroadcastRoom",
			Handler:    _SocketPush_BroadcastRoom_Handler,
		},
		{
			MethodName: "BroadcastGlobal",
			Handler:    _SocketPush_BroadcastGlobal_Handler,
		},
		{
			MethodName: "KickSession",
			Handler:    _SocketPush_KickSession_Handler,
		},
		{
			MethodName: "KickMetaSession",
			Handler:    _SocketPush_KickMetaSession_Handler,
		},
		{
			MethodName: "SendToSession",
			Handler:    _SocketPush_SendToSession_Handler,
		},
		{
			MethodName: "SendToSessions",
			Handler:    _SocketPush_SendToSessions_Handler,
		},
		{
			MethodName: "SendToMetaSession",
			Handler:    _SocketPush_SendToMetaSession_Handler,
		},
		{
			MethodName: "SendToMetaSessions",
			Handler:    _SocketPush_SendToMetaSessions_Handler,
		},
		{
			MethodName: "SocketGtwStat",
			Handler:    _SocketPush_SocketGtwStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "socketpush.proto",
}
