// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ispserver.proto

package server

import (
	"context"

	"zero-service/app/ispserver/internal/logic"
	"zero-service/app/ispserver/internal/svc"
	"zero-service/app/ispserver/ispserver"
)

type IspServerServer struct {
	svcCtx *svc.ServiceContext
	ispserver.UnimplementedIspServerServer
}

func NewIspServerServer(svcCtx *svc.ServiceContext) *IspServerServer {
	return &IspServerServer{
		svcCtx: svcCtx,
	}
}

func (s *IspServerServer) ListSessions(ctx context.Context, in *ispserver.ListSessionsReq) (*ispserver.ListSessionsRes, error) {
	l := logic.NewListSessionsLogic(ctx, s.svcCtx)
	return l.ListSessions(in)
}

func (s *IspServerServer) DisconnectSession(ctx context.Context, in *ispserver.DisconnectSessionReq) (*ispserver.DisconnectSessionRes, error) {
	l := logic.NewDisconnectSessionLogic(ctx, s.svcCtx)
	return l.DisconnectSession(in)
}
