version: '3'

services:
  zero-alarm:
    image: dockerhub.qingcloud.com/zeroservice/zeroalarmdev:latest
    container_name: zeroalarmdev
    volumes:
      - /opt/logs:/opt/logs
    ports:
      - 21002:21002
    tty: true
    stdin_open: true
    network_mode: "host"