// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: logdump.proto

package logdump

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogDump_Ping_FullMethodName    = "/logdump.LogDump/Ping"
	LogDump_PushLog_FullMethodName = "/logdump.LogDump/PushLog"
)

// LogDumpClient is the client API for LogDump service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogDumpClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error)
	// 推送日志
	PushLog(ctx context.Context, in *PushLogReq, opts ...grpc.CallOption) (*PushLogRes, error)
}

type logDumpClient struct {
	cc grpc.ClientConnInterface
}

func NewLogDumpClient(cc grpc.ClientConnInterface) LogDumpClient {
	return &logDumpClient{cc}
}

func (c *logDumpClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingRes)
	err := c.cc.Invoke(ctx, LogDump_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logDumpClient) PushLog(ctx context.Context, in *PushLogReq, opts ...grpc.CallOption) (*PushLogRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushLogRes)
	err := c.cc.Invoke(ctx, LogDump_PushLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogDumpServer is the server API for LogDump service.
// All implementations must embed UnimplementedLogDumpServer
// for forward compatibility.
type LogDumpServer interface {
	Ping(context.Context, *PingReq) (*PingRes, error)
	// 推送日志
	PushLog(context.Context, *PushLogReq) (*PushLogRes, error)
	mustEmbedUnimplementedLogDumpServer()
}

// UnimplementedLogDumpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogDumpServer struct{}

func (UnimplementedLogDumpServer) Ping(context.Context, *PingReq) (*PingRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLogDumpServer) PushLog(context.Context, *PushLogReq) (*PushLogRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushLog not implemented")
}
func (UnimplementedLogDumpServer) mustEmbedUnimplementedLogDumpServer() {}
func (UnimplementedLogDumpServer) testEmbeddedByValue()                 {}

// UnsafeLogDumpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogDumpServer will
// result in compilation errors.
type UnsafeLogDumpServer interface {
	mustEmbedUnimplementedLogDumpServer()
}

func RegisterLogDumpServer(s grpc.ServiceRegistrar, srv LogDumpServer) {
	// If the following call pancis, it indicates UnimplementedLogDumpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogDump_ServiceDesc, srv)
}

func _LogDump_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogDumpServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogDump_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogDumpServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogDump_PushLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogDumpServer).PushLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogDump_PushLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogDumpServer).PushLog(ctx, req.(*PushLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LogDump_ServiceDesc is the grpc.ServiceDesc for LogDump service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogDump_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logdump.LogDump",
	HandlerType: (*LogDumpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LogDump_Ping_Handler,
		},
		{
			MethodName: "PushLog",
			Handler:    _LogDump_PushLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logdump.proto",
}
