// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: trigger.proto

package server

import (
	"context"

	"zero-service/app/trigger/internal/logic"
	"zero-service/app/trigger/internal/svc"
	"zero-service/app/trigger/trigger"
)

type TriggerRpcServer struct {
	svcCtx *svc.ServiceContext
	trigger.UnimplementedTriggerRpcServer
}

func NewTriggerRpcServer(svcCtx *svc.ServiceContext) *TriggerRpcServer {
	return &TriggerRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *TriggerRpcServer) Ping(ctx context.Context, in *trigger.Req) (*trigger.Res, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// 发送 http-post-json 回调
func (s *TriggerRpcServer) SendTrigger(ctx context.Context, in *trigger.SendTriggerReq) (*trigger.SendTriggerRes, error) {
	l := logic.NewSendTriggerLogic(ctx, s.svcCtx)
	return l.SendTrigger(in)
}

// 发送 grpc proto字节码 回调
func (s *TriggerRpcServer) SendProtoTrigger(ctx context.Context, in *trigger.SendProtoTriggerReq) (*trigger.SendProtoTriggerRes, error) {
	l := logic.NewSendProtoTriggerLogic(ctx, s.svcCtx)
	return l.SendProtoTrigger(in)
}

// 获取队列列表
func (s *TriggerRpcServer) Queues(ctx context.Context, in *trigger.QueuesReq) (*trigger.QueuesRes, error) {
	l := logic.NewQueuesLogic(ctx, s.svcCtx)
	return l.Queues(in)
}

// 获取队列信息
func (s *TriggerRpcServer) GetQueueInfo(ctx context.Context, in *trigger.GetQueueInfoReq) (*trigger.GetQueueInfoRes, error) {
	l := logic.NewGetQueueInfoLogic(ctx, s.svcCtx)
	return l.GetQueueInfo(in)
}

// 归档任务
func (s *TriggerRpcServer) ArchiveTask(ctx context.Context, in *trigger.ArchiveTaskReq) (*trigger.ArchiveTaskRes, error) {
	l := logic.NewArchiveTaskLogic(ctx, s.svcCtx)
	return l.ArchiveTask(in)
}

// 删除任务
func (s *TriggerRpcServer) DeleteTask(ctx context.Context, in *trigger.DeleteTaskReq) (*trigger.DeleteTaskRes, error) {
	l := logic.NewDeleteTaskLogic(ctx, s.svcCtx)
	return l.DeleteTask(in)
}

// 获取任务
func (s *TriggerRpcServer) GetTaskInfo(ctx context.Context, in *trigger.GetTaskInfoReq) (*trigger.GetTaskInfoRes, error) {
	l := logic.NewGetTaskInfoLogic(ctx, s.svcCtx)
	return l.GetTaskInfo(in)
}

// 删除所有已完成任务
func (s *TriggerRpcServer) DeleteAllCompletedTasks(ctx context.Context, in *trigger.DeleteAllCompletedTasksReq) (*trigger.DeleteAllCompletedTasksRes, error) {
	l := logic.NewDeleteAllCompletedTasksLogic(ctx, s.svcCtx)
	return l.DeleteAllCompletedTasks(in)
}

// 删除所有已归档任务
func (s *TriggerRpcServer) DeleteAllArchivedTasks(ctx context.Context, in *trigger.DeleteAllArchivedTasksReq) (*trigger.DeleteAllArchivedTasksRes, error) {
	l := logic.NewDeleteAllArchivedTasksLogic(ctx, s.svcCtx)
	return l.DeleteAllArchivedTasks(in)
}

// 获取任务历史统计
func (s *TriggerRpcServer) HistoricalStats(ctx context.Context, in *trigger.HistoricalStatsReq) (*trigger.HistoricalStatsRes, error) {
	l := logic.NewHistoricalStatsLogic(ctx, s.svcCtx)
	return l.HistoricalStats(in)
}

// 获取活跃任务列表
func (s *TriggerRpcServer) ListActiveTasks(ctx context.Context, in *trigger.ListActiveTasksReq) (*trigger.ListActiveTasksRes, error) {
	l := logic.NewListActiveTasksLogic(ctx, s.svcCtx)
	return l.ListActiveTasks(in)
}

// 获取待处理任务列表
func (s *TriggerRpcServer) ListPendingTasks(ctx context.Context, in *trigger.ListPendingTasksReq) (*trigger.ListPendingTasksRes, error) {
	l := logic.NewListPendingTasksLogic(ctx, s.svcCtx)
	return l.ListPendingTasks(in)
}

// 获取聚合任务列表
func (s *TriggerRpcServer) ListAggregatingTasks(ctx context.Context, in *trigger.ListAggregatingTasksReq) (*trigger.ListAggregatingTasksRes, error) {
	l := logic.NewListAggregatingTasksLogic(ctx, s.svcCtx)
	return l.ListAggregatingTasks(in)
}

// 获取预定任务列表
func (s *TriggerRpcServer) ListScheduledTasks(ctx context.Context, in *trigger.ListScheduledTasksReq) (*trigger.ListScheduledTasksRes, error) {
	l := logic.NewListScheduledTasksLogic(ctx, s.svcCtx)
	return l.ListScheduledTasks(in)
}

// 获取重试任务列表
func (s *TriggerRpcServer) ListRetryTasks(ctx context.Context, in *trigger.ListRetryTasksReq) (*trigger.ListRetryTasksRes, error) {
	l := logic.NewListRetryTasksLogic(ctx, s.svcCtx)
	return l.ListRetryTasks(in)
}

// 获取已归档任务列表
func (s *TriggerRpcServer) ListArchivedTasks(ctx context.Context, in *trigger.ListArchivedTasksReq) (*trigger.ListArchivedTasksRes, error) {
	l := logic.NewListArchivedTasksLogic(ctx, s.svcCtx)
	return l.ListArchivedTasks(in)
}

// 获取已完成任务列表
func (s *TriggerRpcServer) ListCompletedTasks(ctx context.Context, in *trigger.ListCompletedTasksReq) (*trigger.ListCompletedTasksRes, error) {
	l := logic.NewListCompletedTasksLogic(ctx, s.svcCtx)
	return l.ListCompletedTasks(in)
}

// 运行任务
func (s *TriggerRpcServer) RunTask(ctx context.Context, in *trigger.RunTaskReq) (*trigger.RunTaskRes, error) {
	l := logic.NewRunTaskLogic(ctx, s.svcCtx)
	return l.RunTask(in)
}

// 计算计划任务日期
func (s *TriggerRpcServer) CalcPlanTaskDate(ctx context.Context, in *trigger.CalcPlanTaskDateReq) (*trigger.CalcPlanTaskDateRes, error) {
	l := logic.NewCalcPlanTaskDateLogic(ctx, s.svcCtx)
	return l.CalcPlanTaskDate(in)
}

// 创建计划任务
func (s *TriggerRpcServer) CreatePlanTask(ctx context.Context, in *trigger.CreatePlanTaskReq) (*trigger.CreatePlanTaskRes, error) {
	l := logic.NewCreatePlanTaskLogic(ctx, s.svcCtx)
	return l.CreatePlanTask(in)
}

// 暂停计划
func (s *TriggerRpcServer) PausePlan(ctx context.Context, in *trigger.PausePlanReq) (*trigger.PausePlanRes, error) {
	l := logic.NewPausePlanLogic(ctx, s.svcCtx)
	return l.PausePlan(in)
}

// 终止计划
func (s *TriggerRpcServer) TerminatePlan(ctx context.Context, in *trigger.TerminatePlanReq) (*trigger.TerminatePlanRes, error) {
	l := logic.NewTerminatePlanLogic(ctx, s.svcCtx)
	return l.TerminatePlan(in)
}

// 恢复计划
func (s *TriggerRpcServer) ResumePlan(ctx context.Context, in *trigger.ResumePlanReq) (*trigger.ResumePlanRes, error) {
	l := logic.NewResumePlanLogic(ctx, s.svcCtx)
	return l.ResumePlan(in)
}

// 暂停计划批次
func (s *TriggerRpcServer) PausePlanBatch(ctx context.Context, in *trigger.PausePlanBatchReq) (*trigger.PausePlanBatchRes, error) {
	l := logic.NewPausePlanBatchLogic(ctx, s.svcCtx)
	return l.PausePlanBatch(in)
}

// 终止计划批次
func (s *TriggerRpcServer) TerminatePlanBatch(ctx context.Context, in *trigger.TerminatePlanBatchReq) (*trigger.TerminatePlanBatchRes, error) {
	l := logic.NewTerminatePlanBatchLogic(ctx, s.svcCtx)
	return l.TerminatePlanBatch(in)
}

// 恢复计划批次
func (s *TriggerRpcServer) ResumePlanBatch(ctx context.Context, in *trigger.ResumePlanBatchReq) (*trigger.ResumePlanBatchRes, error) {
	l := logic.NewResumePlanBatchLogic(ctx, s.svcCtx)
	return l.ResumePlanBatch(in)
}

// 暂停执行项
func (s *TriggerRpcServer) PausePlanExecItem(ctx context.Context, in *trigger.PausePlanExecItemReq) (*trigger.PausePlanExecItemRes, error) {
	l := logic.NewPausePlanExecItemLogic(ctx, s.svcCtx)
	return l.PausePlanExecItem(in)
}

// 终止执行项
func (s *TriggerRpcServer) TerminatePlanExecItem(ctx context.Context, in *trigger.TerminatePlanExecItemReq) (*trigger.TerminatePlanExecItemRes, error) {
	l := logic.NewTerminatePlanExecItemLogic(ctx, s.svcCtx)
	return l.TerminatePlanExecItem(in)
}

// 立即执行计划项
func (s *TriggerRpcServer) RunPlanExecItem(ctx context.Context, in *trigger.RunPlanExecItemReq) (*trigger.RunPlanExecItemRes, error) {
	l := logic.NewRunPlanExecItemLogic(ctx, s.svcCtx)
	return l.RunPlanExecItem(in)
}

// 恢复执行项
func (s *TriggerRpcServer) ResumePlanExecItem(ctx context.Context, in *trigger.ResumePlanExecItemReq) (*trigger.ResumePlanExecItemRes, error) {
	l := logic.NewResumePlanExecItemLogic(ctx, s.svcCtx)
	return l.ResumePlanExecItem(in)
}

// 获取计划详情
func (s *TriggerRpcServer) GetPlan(ctx context.Context, in *trigger.GetPlanReq) (*trigger.GetPlanRes, error) {
	l := logic.NewGetPlanLogic(ctx, s.svcCtx)
	return l.GetPlan(in)
}

// 分页获取计划列表
func (s *TriggerRpcServer) ListPlans(ctx context.Context, in *trigger.ListPlansReq) (*trigger.ListPlansRes, error) {
	l := logic.NewListPlansLogic(ctx, s.svcCtx)
	return l.ListPlans(in)
}

// 获取计划批次详情
func (s *TriggerRpcServer) GetPlanBatch(ctx context.Context, in *trigger.GetPlanBatchReq) (*trigger.GetPlanBatchRes, error) {
	l := logic.NewGetPlanBatchLogic(ctx, s.svcCtx)
	return l.GetPlanBatch(in)
}

// 分页获取计划批次列表
func (s *TriggerRpcServer) ListPlanBatches(ctx context.Context, in *trigger.ListPlanBatchesReq) (*trigger.ListPlanBatchesRes, error) {
	l := logic.NewListPlanBatchesLogic(ctx, s.svcCtx)
	return l.ListPlanBatches(in)
}

// 获取执行项详情
func (s *TriggerRpcServer) GetPlanExecItem(ctx context.Context, in *trigger.GetPlanExecItemReq) (*trigger.GetPlanExecItemRes, error) {
	l := logic.NewGetPlanExecItemLogic(ctx, s.svcCtx)
	return l.GetPlanExecItem(in)
}

// 分页获取执行项列表
func (s *TriggerRpcServer) ListPlanExecItems(ctx context.Context, in *trigger.ListPlanExecItemsReq) (*trigger.ListPlanExecItemsRes, error) {
	l := logic.NewListPlanExecItemsLogic(ctx, s.svcCtx)
	return l.ListPlanExecItems(in)
}

// 获取计划触发日志详情
func (s *TriggerRpcServer) GetPlanExecLog(ctx context.Context, in *trigger.GetPlanExecLogReq) (*trigger.GetPlanExecLogRes, error) {
	l := logic.NewGetPlanExecLogLogic(ctx, s.svcCtx)
	return l.GetPlanExecLog(in)
}

// 分页获取计划触发日志列表
func (s *TriggerRpcServer) ListPlanExecLogs(ctx context.Context, in *trigger.ListPlanExecLogsReq) (*trigger.ListPlanExecLogsRes, error) {
	l := logic.NewListPlanExecLogsLogic(ctx, s.svcCtx)
	return l.ListPlanExecLogs(in)
}

// 回调计划执行项
func (s *TriggerRpcServer) CallbackPlanExecItem(ctx context.Context, in *trigger.CallbackPlanExecItemReq) (*trigger.CallbackPlanExecItemRes, error) {
	l := logic.NewCallbackPlanExecItemLogic(ctx, s.svcCtx)
	return l.CallbackPlanExecItem(in)
}
