// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	pass "zero-service/aiapp/aigtw/internal/handler/pass"
	"zero-service/aiapp/aigtw/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 列出所有可用模型
				Method:  http.MethodGet,
				Path:    "/models",
				Handler: pass.ListModelsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/ai/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 对话补全
				Method:  http.MethodPost,
				Path:    "/chat/completions",
				Handler: pass.ChatCompletionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/ai/v1"),
		rest.WithTimeout(0*time.Nanosecond),
		rest.WithSSE(),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 异步调用 MCP 工具，提交任务后立即返回 task_id
				Method:  http.MethodPost,
				Path:    "/async/tool/call",
				Handler: pass.AsyncToolCallHandler(serverCtx),
			},
			{
				// 查询异步工具调用的执行状态和结果，建议轮询间隔 1~2 秒
				Method:  http.MethodGet,
				Path:    "/async/tool/result/:task_id",
				Handler: pass.AsyncToolResultHandler(serverCtx),
			},
			{
				// 分页查询异步结果列表，支持按状态、时间范围过滤，支持多字段排序
				Method:  http.MethodGet,
				Path:    "/async/tool/results",
				Handler: pass.ListAsyncResultsHandler(serverCtx),
			},
			{
				// 获取异步结果统计信息
				Method:  http.MethodGet,
				Path:    "/async/tool/stats",
				Handler: pass.AsyncResultStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/ai/v1"),
	)
}
