// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	ai "zero-service/aiapp/aigtw/internal/handler/ai"
	aigtw "zero-service/aiapp/aigtw/internal/handler/aigtw"
	"zero-service/aiapp/aigtw/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 列出可用模型
				Method:  http.MethodGet,
				Path:    "/models",
				Handler: ai.ListModelsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/aigtw/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 对话补全
				Method:  http.MethodPost,
				Path:    "/chat/completions",
				Handler: ai.ChatCompletionsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/aigtw/v1"),
		rest.WithTimeout(0*time.Nanosecond),
		rest.WithSSE(),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// ping
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: aigtw.PingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/aigtw/v1"),
	)
}
