// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: geo.proto

package server

import (
	"context"

	"zero-service/app/geo/geo"
	"zero-service/app/geo/internal/logic"
	"zero-service/app/geo/internal/svc"
)

type GeoServer struct {
	svcCtx *svc.ServiceContext
	geo.UnimplementedGeoServer
}

func NewGeoServer(svcCtx *svc.ServiceContext) *GeoServer {
	return &GeoServer{
		svcCtx: svcCtx,
	}
}

func (s *GeoServer) Ping(ctx context.Context, in *geo.Req) (*geo.Res, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
