syntax = "proto3";

package zerorpc;
option go_package = "./zerorpc";

message Req {
  string ping = 1 [json_name = "ping"];
}

message Res {
  string pong = 1 [json_name = "pong"];
}

message SendDelayTaskReq {
  string msg_id = 1 [json_name = "msgId"]; // 唯一消息 id
  string type = 2 [json_name = "type"];
  string body = 3 [json_name = "body"];
  int64 process_in = 4 [json_name = "processIn"]; // 分钟
}

message SendDelayTaskRes {
}

message ForwardTaskReq {
  string msg_id = 1 [json_name = "msgId"]; // 唯一消息 id
  string body = 2 [json_name = "body"];
  int64 process_in = 3 [json_name = "processIn"]; // 秒
  string trigger_time = 4 [json_name = "triggerTime"]; // 触发时间 2019-01-01 00:00:00 二选一
  string url = 5 [json_name = "url"]; // 转发地址 POST json提交
}

message ForwardTaskRes {
}

message SendSMSVerifyCodeReq {
  string mobile = 1 [json_name = "mobile"];
}

message SendSMSVerifyCodeRes {
  string code = 1 [json_name = "code"];
}

message GetRegionListReq {
  string parent_code = 1 [json_name = "parentCode"];
}

message GetRegionListRes {
  repeated Region region = 1 [json_name = "region"];
}

message Region {
  string code = 1 [json_name = "code"]; // 区划编号
  string parent_code = 2 [json_name = "parentCode"]; // 父区划编号
  string name = 3 [json_name = "name"]; // 区划名称
  string province_code = 4 [json_name = "provinceCode"]; // 省级区划编号
  string province_name = 5 [json_name = "provinceName"]; // 省级名称
  string city_code = 6 [json_name = "cityCode"]; // 市级区划编号
  string city_name = 7 [json_name = "cityName"]; // 市级名称
  string district_code = 8 [json_name = "districtCode"]; // 区级区划编号
  string district_name = 9 [json_name = "districtName"]; // 区级名称
  int64 region_level = 10 [json_name = "regionLevel"]; // 层级
}

message GenerateTokenReq {
  int64 user_id = 1 [json_name = "userId"];
}

message GenerateTokenRes {
  string access_token = 1 [json_name = "accessToken"];
  int64  access_expire = 2 [json_name = "accessExpire"];
  int64  refresh_after = 3 [json_name = "refreshAfter"];
}

message LoginReq{
  string auth_type = 1 [json_name = "authType"]; // miniProgram-小程序一键登录,mobile-手机号,unionId-微信unionId
  string auth_key = 2 [json_name = "authKey"]; // miniProgram-Code,mobile-验证码,unionId-sessionKey
  string password = 3 [json_name = "password"];
}

message LoginRes{
  string access_token = 1 [json_name = "accessToken"];
  int64  access_expire = 2 [json_name = "accessExpire"];
  int64  refresh_after = 3 [json_name = "refreshAfter"];
}

message MiniProgramLoginReq{
  string code = 1 [json_name = "code"];
}

message MiniProgramLoginRes{
  string open_id = 1 [json_name = "openId"];
  string union_id = 2 [json_name = "unionId"];
  string session_key = 3 [json_name = "sessionKey"];
}

message GetUserInfoReq {
  string id = 1 [json_name = "id"];
}

message GetUserInfoRes {
  User user = 1 [json_name = "user"];
}

message EditUserInfoReq {
  int64 id = 1 [json_name = "id"];
  string mobile = 2 [json_name = "mobile"];
  string nickname = 3 [json_name = "nickname"];
  int64  sex = 4 [json_name = "sex"];
  string avatar = 5 [json_name = "avatar"];
}

message EditUserInfoRes {
}

message User {
  int64 id = 1 [json_name = "id"];
  string mobile = 2 [json_name = "mobile"];
  string nickname = 3 [json_name = "nickname"];
  int64  sex = 4 [json_name = "sex"];
  string avatar = 5 [json_name = "avatar"];
  string open_id = 6 [json_name = "openId"];
}

message WxPayJsApiReq {
  string open_id = 1 [json_name = "openId"];
  string mch_id = 2 [json_name = "mchId"]; // 商户id
  string mch_order_no = 3 [json_name = "mchOrderNo"]; // 商户订单号
  int64 txn_amt = 4 [json_name = "txnAmt"]; // 支付金额 分
  int64 real_amt = 5 [json_name = "realAmt"]; // 实付金额 分
  string body = 6 [json_name = "body"]; // 商品描述信息
  int64 user_id = 7 [json_name = "userId"]; // 用户id
}

message WxPayJsApiRes {
  string txn_id = 1 [json_name = "txnId"]; // 支付订单号
  string pay_conf = 2 [json_name = "payConf"]; // 调起支付 json
  string prepay_id = 7 [json_name = "prepayId"]; // 预支付交易会话标识
}

service Zerorpc {
  rpc Ping(Req) returns(Res);
  // 发送延迟任务
  rpc SendDelayTask(SendDelayTaskReq) returns(SendDelayTaskRes);
  // 转发任务
  rpc ForwardTask(ForwardTaskReq) returns(ForwardTaskRes);

  // 发送手机号验证码
  rpc SendSMSVerifyCode(SendSMSVerifyCodeReq) returns(SendSMSVerifyCodeRes);

  // 获取区域列表
  rpc GetRegionList(GetRegionListReq) returns(GetRegionListRes);

  // 生成 token
  rpc GenerateToken(GenerateTokenReq) returns(GenerateTokenRes);
  // 登录
  rpc Login (LoginReq) returns (LoginRes);
  // 小程序登录
  rpc MiniProgramLogin (MiniProgramLoginReq) returns (MiniProgramLoginRes);
  // 用户详情
  rpc GetUserInfo(GetUserInfoReq) returns (GetUserInfoRes);
  // 编辑用户
  rpc EditUserInfo(EditUserInfoReq) returns (EditUserInfoRes);

  // JSAPI支付
  rpc WxPayJsApi (WxPayJsApiReq) returns (WxPayJsApiRes);
}
