// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: bridgemqtt.proto

package server

import (
	"context"

	"zero-service/app/bridgemqtt/bridgemqtt"
	"zero-service/app/bridgemqtt/internal/logic"
	"zero-service/app/bridgemqtt/internal/svc"
)

type BridgeMqttServer struct {
	svcCtx *svc.ServiceContext
	bridgemqtt.UnimplementedBridgeMqttServer
}

func NewBridgeMqttServer(svcCtx *svc.ServiceContext) *BridgeMqttServer {
	return &BridgeMqttServer{
		svcCtx: svcCtx,
	}
}

func (s *BridgeMqttServer) Ping(ctx context.Context, in *bridgemqtt.Req) (*bridgemqtt.Res, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
