// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: iecrpc.proto

package server

import (
	"context"

	"zero-service/app/iecrpc/iecrpc"
	"zero-service/app/iecrpc/internal/logic"
	"zero-service/app/iecrpc/internal/svc"
)

type IecrpcServer struct {
	svcCtx *svc.ServiceContext
	iecrpc.UnimplementedIecrpcServer
}

func NewIecrpcServer(svcCtx *svc.ServiceContext) *IecrpcServer {
	return &IecrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *IecrpcServer) Ping(ctx context.Context, in *iecrpc.Req) (*iecrpc.Res, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
