// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: djigateway.proto

package djigateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DjiGateway_Ping_FullMethodName                 = "/djigateway.DjiGateway/Ping"
	DjiGateway_ExecuteFlightTask_FullMethodName    = "/djigateway.DjiGateway/ExecuteFlightTask"
	DjiGateway_SendCustomDataToPsdk_FullMethodName = "/djigateway.DjiGateway/SendCustomDataToPsdk"
)

// DjiGatewayClient is the client API for DjiGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DjiGatewayClient interface {
	Ping(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	ExecuteFlightTask(ctx context.Context, in *FlightTaskReq, opts ...grpc.CallOption) (*CommonRes, error)
	SendCustomDataToPsdk(ctx context.Context, in *CustomDataToPsdkReq, opts ...grpc.CallOption) (*CommonRes, error)
}

type djiGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewDjiGatewayClient(cc grpc.ClientConnInterface) DjiGatewayClient {
	return &djiGatewayClient{cc}
}

func (c *djiGatewayClient) Ping(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Res)
	err := c.cc.Invoke(ctx, DjiGateway_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *djiGatewayClient) ExecuteFlightTask(ctx context.Context, in *FlightTaskReq, opts ...grpc.CallOption) (*CommonRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRes)
	err := c.cc.Invoke(ctx, DjiGateway_ExecuteFlightTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *djiGatewayClient) SendCustomDataToPsdk(ctx context.Context, in *CustomDataToPsdkReq, opts ...grpc.CallOption) (*CommonRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonRes)
	err := c.cc.Invoke(ctx, DjiGateway_SendCustomDataToPsdk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DjiGatewayServer is the server API for DjiGateway service.
// All implementations must embed UnimplementedDjiGatewayServer
// for forward compatibility.
type DjiGatewayServer interface {
	Ping(context.Context, *Req) (*Res, error)
	ExecuteFlightTask(context.Context, *FlightTaskReq) (*CommonRes, error)
	SendCustomDataToPsdk(context.Context, *CustomDataToPsdkReq) (*CommonRes, error)
	mustEmbedUnimplementedDjiGatewayServer()
}

// UnimplementedDjiGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDjiGatewayServer struct{}

func (UnimplementedDjiGatewayServer) Ping(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDjiGatewayServer) ExecuteFlightTask(context.Context, *FlightTaskReq) (*CommonRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteFlightTask not implemented")
}
func (UnimplementedDjiGatewayServer) SendCustomDataToPsdk(context.Context, *CustomDataToPsdkReq) (*CommonRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCustomDataToPsdk not implemented")
}
func (UnimplementedDjiGatewayServer) mustEmbedUnimplementedDjiGatewayServer() {}
func (UnimplementedDjiGatewayServer) testEmbeddedByValue()                    {}

// UnsafeDjiGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DjiGatewayServer will
// result in compilation errors.
type UnsafeDjiGatewayServer interface {
	mustEmbedUnimplementedDjiGatewayServer()
}

func RegisterDjiGatewayServer(s grpc.ServiceRegistrar, srv DjiGatewayServer) {
	// If the following call pancis, it indicates UnimplementedDjiGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DjiGateway_ServiceDesc, srv)
}

func _DjiGateway_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DjiGatewayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DjiGateway_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DjiGatewayServer).Ping(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _DjiGateway_ExecuteFlightTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlightTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DjiGatewayServer).ExecuteFlightTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DjiGateway_ExecuteFlightTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DjiGatewayServer).ExecuteFlightTask(ctx, req.(*FlightTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DjiGateway_SendCustomDataToPsdk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomDataToPsdkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DjiGatewayServer).SendCustomDataToPsdk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DjiGateway_SendCustomDataToPsdk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DjiGatewayServer).SendCustomDataToPsdk(ctx, req.(*CustomDataToPsdkReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DjiGateway_ServiceDesc is the grpc.ServiceDesc for DjiGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DjiGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "djigateway.DjiGateway",
	HandlerType: (*DjiGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DjiGateway_Ping_Handler,
		},
		{
			MethodName: "ExecuteFlightTask",
			Handler:    _DjiGateway_ExecuteFlightTask_Handler,
		},
		{
			MethodName: "SendCustomDataToPsdk",
			Handler:    _DjiGateway_SendCustomDataToPsdk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "djigateway.proto",
}
