syntax = "proto3";

package socketgtw;
option go_package = "./socketgtw";
option java_multiple_files = true;
option java_package = "com.github.socketgtw.grpc";
option java_outer_classname = "SocketGtwProto";

service SocketGtw {
  // 加入房间
  rpc JoinRoom(JoinRoomReq) returns (JoinRoomRes);
  // 离开房间
  rpc LeaveRoom(LeaveRoomReq) returns (LeaveRoomRes);
  // 向指定房间广播消息
  rpc BroadcastRoom(BroadcastRoomReq) returns (BroadcastRoomRes);
  // 向所有在线前端广播消息
  rpc BroadcastGlobal(BroadcastGlobalReq) returns (BroadcastGlobalRes);
  // 剔除 session
  rpc KickSession(KickSessionReq) returns (KickSessionRes);
  // 指定元数据剔除 session
  rpc KickMetaSession(KickMetaSessionReq) returns (KickMetaSessionRes);
  // 向指定 session 发送消息
  rpc SendToSession(SendToSessionReq) returns (SendToSessionRes);
  // 向指定 session 批量发送消息
  rpc SendToSessions(SendToSessionsReq) returns (SendToSessionsRes);
  // 向指定元数据 session 发送消息
  rpc SendToMetaSession(SendToMetaSessionReq) returns (SendToMetaSessionRes);
  // 向指定元数据 session 批量发送消息
  rpc SendToMetaSessions(SendToMetaSessionsReq) returns (SendToMetaSessionsRes);
  // 获取网关统计信息
  rpc SocketGtwStat(SocketGtwStatReq) returns (SocketGtwStatRes);
}

message PbMetaSession{
  string key = 1 [json_name = "key"];
  string value = 2 [json_name = "value"];
}

message JoinRoomReq {
  string req_id = 1 [json_name = "reqId"];
  string socket_id = 2 [json_name = "socketId"];
  string room = 3 [json_name = "room"];
}

message JoinRoomRes {
  string req_id = 1 [json_name = "reqId"];
}

message LeaveRoomReq {
  string req_id = 1 [json_name = "reqId"];
  string socket_id = 2 [json_name = "socketId"];
  string room = 3 [json_name = "room"];
}

message LeaveRoomRes {
  string req_id = 1 [json_name = "reqId"];
}

message BroadcastRoomReq {
  string req_id = 1 [json_name = "reqId"];
  string room = 2 [json_name = "room"];
  string event = 3 [json_name = "event"];
  string payload = 4 [json_name = "payload"];
}

message BroadcastRoomRes {
  string req_id = 1 [json_name = "reqId"];
}

message BroadcastGlobalReq {
  string req_id = 1 [json_name = "reqId"];
  string event = 2 [json_name = "event"];
  string payload = 3 [json_name = "payload"];
}

message BroadcastGlobalRes {
  string req_id = 1 [json_name = "reqId"];
}

message KickSessionReq {
  string req_id = 1 [json_name = "reqId"];
  string socket_id = 2 [json_name = "socketId"];
}

message KickSessionRes {
  string req_id = 1 [json_name = "reqId"];
}

message KickMetaSessionReq {
  string req_id = 1 [json_name = "reqId"];
  string key = 2 [json_name = "key"];
  string value = 3 [json_name = "value"];
}

message KickMetaSessionRes {
  string req_id = 1 [json_name = "reqId"];
}

message SendToSessionReq {
  string req_id = 1 [json_name = "reqId"];
  string socket_id = 2 [json_name = "socketId"];
  string event = 3 [json_name = "event"];
  string payload = 4 [json_name = "payload"];
}

message SendToSessionRes {
  string req_id = 1 [json_name = "reqId"];
}

message SendToSessionsReq {
  string req_id = 1 [json_name = "reqId"];
  repeated string socket_ids = 2 [json_name = "socketIds"];
  string event = 3 [json_name = "event"];
  string payload = 4 [json_name = "payload"];
}

message SendToSessionsRes {
  string req_id = 1 [json_name = "reqId"];
}

message SendToMetaSessionReq {
  string req_id = 1 [json_name = "reqId"];
  string key = 2 [json_name = "key"];
  string value = 3 [json_name = "value"];
  string event = 4 [json_name = "event"];
  string payload = 5 [json_name = "payload"];
}

message SendToMetaSessionRes {
  string req_id = 1 [json_name = "reqId"];
}

message SendToMetaSessionsReq {
  string req_id = 1 [json_name = "reqId"];
  repeated PbMetaSession meta_sessions = 2 [json_name = "metaSessions"];
  string event = 3 [json_name = "event"];
  string payload = 4 [json_name = "payload"];
}

message SendToMetaSessionsRes {
  string req_id = 1 [json_name = "reqId"];
}

message SocketGtwStatReq {
}

message SocketGtwStatRes {
  int64 sessions = 1 [json_name = "sessions"];
}
