// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AsyncResultStatsResponse struct {
	Total       int64   `json:"total"`        // 任务总数
	Pending     int64   `json:"pending"`      // 待处理任务数
	Completed   int64   `json:"completed"`    // 已完成任务数
	Failed      int64   `json:"failed"`       // 失败任务数
	SuccessRate float64 `json:"success_rate"` // 成功率
}

type AsyncToolCallRequest struct {
	Server string                 `json:"server"` // MCP 服务器名称
	Tool   string                 `json:"tool"`   // MCP 工具名称
	Args   map[string]interface{} `json:"args"`   // 工具参数
}

type AsyncToolCallResponse struct {
	TaskID string `json:"task_id"` // 任务唯一标识符
	Status string `json:"status"`  // 任务初始状态，固定为 "pending"
}

type AsyncToolResultRequest struct {
	TaskID string `path:"task_id"`
}

type AsyncToolResultResponse struct {
	TaskID   string            `json:"task_id"`            // 任务标识符
	Status   string            `json:"status"`             // 状态: pending / running / completed / failed
	Progress float64           `json:"progress"`           // 执行进度 0.0~100.0
	Result   string            `json:"result,omitempty"`   // 成功结果
	Error    string            `json:"error,omitempty"`    // 失败错误
	Messages []ProgressMessage `json:"messages,omitempty"` // 进度消息历史
}

type ChatCompletionChunk struct {
	Id      string        `json:"id"`      // 补全ID
	Object  string        `json:"object"`  // 固定值 "chat.completion.chunk"
	Created int64         `json:"created"` // 创建时间
	Model   string        `json:"model"`   // 模型ID
	Choices []ChunkChoice `json:"choices"` // 选项列表
}

type ChatCompletionRequest struct {
	Model       string        `json:"model"`                                        // 模型ID，对应能力
	Messages    []ChatMessage `json:"messages"`                                     // 对话消息列表
	Stream      bool          `json:"stream,optional"`                              // 是否启用 SSE 流式输出
	Temperature float64       `json:"temperature,optional,default=1,range=[0:2.0]"` // 采样温度
	TopP        float64       `json:"top_p,optional,default=1,range=[0:1.0]"`       // 核采样概率
	MaxTokens   int           `json:"max_tokens,optional"`                          // 最大生成 token 数
	Stop        []string      `json:"stop,optional"`                                // 停止生成的标记序列
	User        string        `json:"user,optional"`                                // 终端用户标识
	Thinking    ThinkingParam `json:"thinking,optional"`                            // 深度思考模式参数
}

type ChatCompletionResponse struct {
	Id      string   `json:"id"`      // 补全ID
	Object  string   `json:"object"`  // 固定值 "chat.completion"
	Created int64    `json:"created"` // 创建时间
	Model   string   `json:"model"`   // 实际使用的模型ID
	Choices []Choice `json:"choices"` // 补全结果列表
	Usage   Usage    `json:"usage"`   // Token 用量统计
}

type ChatDelta struct {
	Role             string          `json:"role,optional"`              // 角色
	Content          string          `json:"content,optional"`           // 内容增量
	ReasoningContent string          `json:"reasoning_content,optional"` // 推理思考过程增量
	ToolCalls        []ToolCallDelta `json:"tool_calls,optional"`        // 工具调用增量
}

type HealthResponse struct {
	Status       string            `json:"status"`       // 服务状态: ok/error
	Version      string            `json:"version"`      // 服务版本
	Timestamp    int64             `json:"timestamp"`    // 响应时间戳
	Dependencies map[string]string `json:"dependencies"` // 依赖服务状态
}

type ChatMessage struct {
	Role             string `json:"role"`                       // 角色: system / user / assistant
	Content          string `json:"content"`                    // 消息内容
	ReasoningContent string `json:"reasoning_content,optional"` // 模型推理思考过程
}

type Choice struct {
	Index        int         `json:"index"`         // 选项索引
	Message      ChatMessage `json:"message"`       // 完整的助手消息
	FinishReason string      `json:"finish_reason"` // 结束原因: stop / length / content_filter
}

type ChunkChoice struct {
	Index        int       `json:"index"`                  // 选项索引
	Delta        ChatDelta `json:"delta"`                  // 增量内容
	FinishReason *string   `json:"finish_reason,optional"` // 结束原因: stop / length / content_filter / tool_calls
}

type ListAsyncResultsRequest struct {
	Status    string `form:"status,optional"`     // 过滤状态
	StartTime int64  `form:"start_time,optional"` // 开始时间戳（毫秒）
	EndTime   int64  `form:"end_time,optional"`   // 结束时间戳（毫秒）
	Page      int    `form:"page,optional"`       // 页码
	PageSize  int    `form:"page_size,optional"`  // 每页数量
	SortField string `form:"sort_field,optional"` // 排序字段
	SortOrder string `form:"sort_order,optional"` // 排序方向
}

type ListAsyncResultsResponse struct {
	Items      []AsyncToolResultResponse `json:"items"`       // 任务列表
	Total      int64                     `json:"total"`       // 总数
	Page       int                       `json:"page"`        // 当前页
	PageSize   int                       `json:"page_size"`   // 每页数量
	TotalPages int                       `json:"total_pages"` // 总页数
}

type ListModelsResponse struct {
	Object string        `json:"object"` // 固定值 "list"
	Data   []ModelObject `json:"data"`   // 模型列表
}

type ModelMetadata struct {
	DisplayName       string `json:"display_name"`       // 能力显示名称
	Description       string `json:"description"`        // 能力描述
	SupportsStreaming bool   `json:"supports_streaming"` // 是否支持流式输出
}

type ModelObject struct {
	Id       string         `json:"id"`                // 模型ID
	Object   string         `json:"object"`            // 固定值 "model"
	Created  int64          `json:"created"`           // 创建时间
	OwnedBy  string         `json:"owned_by"`          // 所属方
	Metadata *ModelMetadata `json:"metadata,optional"` // 扩展元数据
}

type ProgressMessage struct {
	Progress float64 `json:"progress"` // 当前进度百分比，0.0~100.0
	Total    float64 `json:"total"`    // 进度总值（参考值）
	Message  string  `json:"message"`  // 消息内容
	Time     int64   `json:"time"`     // 时间戳，Unix 秒
}

type SoloAgentInfo struct {
	Type         string   `json:"type"`         // Agent 类型
	Name         string   `json:"name"`         // Agent 名称
	Description  string   `json:"description"`  // Agent 描述
	Capabilities []string `json:"capabilities"` // 能力列表
	Available    bool     `json:"available"`    // 是否可用
}

type SoloChatRequest struct {
	SessionId string `json:"sessionId"`          // 会话 ID（空则创建新会话）
	Message   string `json:"message"`            // 消息内容
	AgentMode string `json:"agentMode,optional"` // Agent 模式: auto, fast, deep
}

type SoloChatResponse struct {
}

type SoloCreateSessionRequest struct {
	Title string `json:"title,optional"` // 会话标题
}

type SoloCreateSessionResponse struct {
	Session *SoloSessionInfo `json:"session"` // 会话信息
}

type SoloDeleteSessionRequest struct {
	SessionId string `path:"id"` // 会话 ID
}

type SoloDeleteSessionResponse struct {
	Success bool `json:"success"` // 是否成功
}

type SoloGetSessionRequest struct {
	SessionId string `path:"id"` // 会话 ID
}

type SoloGetSessionResponse struct {
	Session *SoloSessionInfo `json:"session"` // 会话信息
}

type SoloHealthResponse struct {
	Status  string `json:"status"`  // 状态
	Version string `json:"version"` // 版本
}

type SoloInterruptRequest struct {
	InterruptId string   `json:"interruptId"` // 中断 ID
	Approved    bool     `json:"approved"`    // 是否批准
	SelectedIds []string `json:"selectedIds"` // 选中的选项 ID
	Reason      string   `json:"reason"`      // 拒绝原因
}

type SoloInterruptResponse struct {
	Success     bool   `json:"success"`     // 是否成功
	Message     string `json:"message"`     // 消息
	InterruptId string `json:"interruptId"` // 中断 ID
}

type SoloListAgentsResponse struct {
	Agents []*SoloAgentInfo `json:"agents"` // Agent 列表
}

type SoloListSessionsRequest struct {
	Page     int `json:"page,optional"`     // 页码
	PageSize int `json:"pageSize,optional"` // 每页数量
}

type SoloListSessionsResponse struct {
	Sessions []*SoloSessionInfo `json:"sessions"` // 会话列表
	Total    int                `json:"total"`    // 总数
}

type SoloSessionInfo struct {
	SessionId    string `json:"sessionId"`    // 会话 ID
	UserId       string `json:"userId"`       // 用户 ID
	AgentMode    string `json:"agentMode"`    // Agent 模式
	Title        string `json:"title"`        // 会话标题
	CreatedAt    int64  `json:"createdAt"`    // 创建时间
	UpdatedAt    int64  `json:"updatedAt"`    // 更新时间
	MessageCount int    `json:"messageCount"` // 消息数量
	LastMessage  string `json:"lastMessage"`  // 最后一条消息
}

type SoloSwitchAgentRequest struct {
	SessionId   string `json:"sessionId"`   // 会话 ID
	AgentMode   string `json:"agentMode"`   // Agent 模式
	KeepContext bool   `json:"keepContext"` // 保持上下文
}

type SoloSwitchAgentResponse struct {
	Session  *SoloSessionInfo `json:"session"`  // 会话信息
	NewAgent *SoloAgentInfo   `json:"newAgent"` // 新的 Agent
}

type SoloToolInfo struct {
	Name        string `json:"name"`        // 工具名称
	Description string `json:"description"` // 工具描述
}

type ThinkingParam struct {
	Type string `json:"type"` // "enabled" 启用 / "disabled" 禁用
}

type ToolCallDelta struct {
	Index    int                   `json:"index,omitempty"`    // 工具调用索引
	Id       string                `json:"id,omitempty"`       // 工具调用ID
	Type     string                `json:"type,omitempty"`     // 类型，通常为 "function"
	Function ToolCallFunctionDelta `json:"function,omitempty"` // 函数信息
}

type ToolCallFunctionDelta struct {
	Name      string `json:"name,omitempty"`      // 函数名称
	Arguments string `json:"arguments,omitempty"` // 参数JSON字符串（可能分片到达）
}

type Usage struct {
	PromptTokens     int `json:"prompt_tokens"`     // 提示词 token 数
	CompletionTokens int `json:"completion_tokens"` // 补全 token 数
	TotalTokens      int `json:"total_tokens"`      // 总 token 数
}
