// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ispserver.proto

package ispserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceCode    string                 `protobuf:"bytes,2,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	ConnectedAt   int64                  `protobuf:"varint,4,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_ispserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ispserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_ispserver_proto_rawDescGZIP(), []int{0}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *SessionInfo) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *SessionInfo) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

type ListSessionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsReq) Reset() {
	*x = ListSessionsReq{}
	mi := &file_ispserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsReq) ProtoMessage() {}

func (x *ListSessionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ispserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsReq.ProtoReflect.Descriptor instead.
func (*ListSessionsReq) Descriptor() ([]byte, []int) {
	return file_ispserver_proto_rawDescGZIP(), []int{1}
}

type ListSessionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRes) Reset() {
	*x = ListSessionsRes{}
	mi := &file_ispserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRes) ProtoMessage() {}

func (x *ListSessionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_ispserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRes.ProtoReflect.Descriptor instead.
func (*ListSessionsRes) Descriptor() ([]byte, []int) {
	return file_ispserver_proto_rawDescGZIP(), []int{2}
}

func (x *ListSessionsRes) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type DisconnectSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectSessionReq) Reset() {
	*x = DisconnectSessionReq{}
	mi := &file_ispserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectSessionReq) ProtoMessage() {}

func (x *DisconnectSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_ispserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectSessionReq.ProtoReflect.Descriptor instead.
func (*DisconnectSessionReq) Descriptor() ([]byte, []int) {
	return file_ispserver_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectSessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DisconnectSessionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectSessionRes) Reset() {
	*x = DisconnectSessionRes{}
	mi := &file_ispserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectSessionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectSessionRes) ProtoMessage() {}

func (x *DisconnectSessionRes) ProtoReflect() protoreflect.Message {
	mi := &file_ispserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectSessionRes.ProtoReflect.Descriptor instead.
func (*DisconnectSessionRes) Descriptor() ([]byte, []int) {
	return file_ispserver_proto_rawDescGZIP(), []int{4}
}

var File_ispserver_proto protoreflect.FileDescriptor

const file_ispserver_proto_rawDesc = "" +
	"\n" +
	"\x0fispserver.proto\x12\tispserver\"\x91\x01\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vdevice_code\x18\x02 \x01(\tR\n" +
	"deviceCode\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x12!\n" +
	"\fconnected_at\x18\x04 \x01(\x03R\vconnectedAt\"\x11\n" +
	"\x0fListSessionsReq\"E\n" +
	"\x0fListSessionsRes\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.ispserver.SessionInfoR\bsessions\"5\n" +
	"\x14DisconnectSessionReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14DisconnectSessionRes2\xaa\x01\n" +
	"\tIspServer\x12F\n" +
	"\fListSessions\x12\x1a.ispserver.ListSessionsReq\x1a\x1a.ispserver.ListSessionsRes\x12U\n" +
	"\x11DisconnectSession\x12\x1f.ispserver.DisconnectSessionReq\x1a\x1f.ispserver.DisconnectSessionResB\rZ\v./ispserverb\x06proto3"

var (
	file_ispserver_proto_rawDescOnce sync.Once
	file_ispserver_proto_rawDescData []byte
)

func file_ispserver_proto_rawDescGZIP() []byte {
	file_ispserver_proto_rawDescOnce.Do(func() {
		file_ispserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ispserver_proto_rawDesc), len(file_ispserver_proto_rawDesc)))
	})
	return file_ispserver_proto_rawDescData
}

var file_ispserver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ispserver_proto_goTypes = []any{
	(*SessionInfo)(nil),          // 0: ispserver.SessionInfo
	(*ListSessionsReq)(nil),      // 1: ispserver.ListSessionsReq
	(*ListSessionsRes)(nil),      // 2: ispserver.ListSessionsRes
	(*DisconnectSessionReq)(nil), // 3: ispserver.DisconnectSessionReq
	(*DisconnectSessionRes)(nil), // 4: ispserver.DisconnectSessionRes
}
var file_ispserver_proto_depIdxs = []int32{
	0, // 0: ispserver.ListSessionsRes.sessions:type_name -> ispserver.SessionInfo
	1, // 1: ispserver.IspServer.ListSessions:input_type -> ispserver.ListSessionsReq
	3, // 2: ispserver.IspServer.DisconnectSession:input_type -> ispserver.DisconnectSessionReq
	2, // 3: ispserver.IspServer.ListSessions:output_type -> ispserver.ListSessionsRes
	4, // 4: ispserver.IspServer.DisconnectSession:output_type -> ispserver.DisconnectSessionRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ispserver_proto_init() }
func file_ispserver_proto_init() {
	if File_ispserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ispserver_proto_rawDesc), len(file_ispserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ispserver_proto_goTypes,
		DependencyIndexes: file_ispserver_proto_depIdxs,
		MessageInfos:      file_ispserver_proto_msgTypes,
	}.Build()
	File_ispserver_proto = out.File
	file_ispserver_proto_goTypes = nil
	file_ispserver_proto_depIdxs = nil
}
